import type { PrismaModel } from '@tg-scripts/types';
import { getResourceName } from '../../generator/utils';

type FieldDirectiveMetadata = Record<
  string,
  Record<
    string,
    {
      format?: string | undefined;
      upload?: { type: string };
      readOnly?: boolean;
    }
  >
>;

export const buildFieldDirectiveMetadata = (models: PrismaModel[]): FieldDirectiveMetadata => {
  const result: FieldDirectiveMetadata = {};

  models.forEach((model) => {
    const resourceName = getResourceName(model.name);
    const fieldsWithDirectives = model.fields.reduce<Record<string, FieldDirectiveMetadata[string][string]>>(
      (acc, field) => {
        const fieldConfig: FieldDirectiveMetadata[string][string] = {};

        if (field.tgFormat) {
          fieldConfig.format = field.tgFormat;
        }
        if (field.tgUpload) {
          fieldConfig.upload = { type: field.tgUpload };
        }
        if (field.tgReadOnly) {
          fieldConfig.readOnly = true;
        }

        if (Object.keys(fieldConfig).length > 0) {
          acc[field.name] = fieldConfig;
        }

        return acc;
      },
      {},
    );

    if (Object.keys(fieldsWithDirectives).length > 0) {
      result[resourceName] = fieldsWithDirectives;
    }
  });

  return result;
};

export const buildFieldDirectiveFile = (models: PrismaModel[]): string => {
  const metadata = buildFieldDirectiveMetadata(models);
  const serialized = JSON.stringify(metadata, null, 2);

  return `/**
 * AUTO-GENERATED FILE
 * This file was automatically generated by the DashboardGenerator.
 * Do not edit this file manually. Instead, modify the Prisma schema directives and regenerate.
 */

export const fieldDirectiveConfig = ${serialized} as const;
`;
};
