import * as fs from 'fs';
import * as path from 'path';
import { getResourceName, toKebabCase, pluralize, toCamelCase } from './src/generator/utils';
import type { PrismaModel, GeneratedModuleFolder, Config } from '@tg-scripts/types';
import { tagAutoGenerated } from './src/generator/utils';
import { promptUser, formatGeneratedFile, formatGeneratedFiles } from './src/io/utils';
import { ModulePathResolver } from './src/io/module-path-resolver/ModulePathResolver';
import { NestAppModuleUpdater } from './src/generator/nest-app-module-updater/NestAppModuleUpdater';
import { NestModuleUpdater } from './src/generator/nest-module-updater/NestModuleUpdater';
import { DataProviderEndpointGenerator } from './src/generator/data-provider-endpoint-generator/DataProviderEndpointGenerator';
import { PrismaSchemaParser } from './src/parser/prisma-schema-parser/PrismaSchemaParser';
import { PrismaFieldParser } from './src/parser/prisma-field-parser/PrismaFieldParser';
import { NestServiceGenerator } from './src/generator/nest-service-generator/NestServiceGenerator';
import { NestControllerGenerator } from './src/generator/nest-controller-generator/NestControllerGenerator';
import { NestStaticGenerator } from './src/generator/nest-static-generator/NestStaticGenerator';
import { NestDtoGenerator } from './src/generator/nest-dto-generator/NestDtoGenerator';
import { PrismaRelationsParser } from './src/parser/prisma-relation-parser/PrismaRelationsParser';
import { NestModuleFileGenerator } from './src/generator/nest-module-file-generator/NestModuleFileGenerator';
import { config } from './config';

export class ApiGenerator {
  private models: PrismaModel[] = [];
  private enums: Map<string, string[]> = new Map();
  private autoCreatedModules: {
    name: string;
    moduleType: GeneratedModuleFolder;
  }[] = [];

  private config: Config;
  private fieldParser: PrismaFieldParser;
  private fieldRelationsParser: PrismaRelationsParser;
  private schemaParser: PrismaSchemaParser;
  private dtoGenerator: NestDtoGenerator;
  private moduleFileGenerator: NestModuleFileGenerator;
  private serviceGenerator: NestServiceGenerator;
  private controllerGenerator: NestControllerGenerator;
  private modulePathResolver: ModulePathResolver;
  private appModuleUpdater: NestAppModuleUpdater;
  private moduleUpdater: NestModuleUpdater;
  private dataProviderGenerator: DataProviderEndpointGenerator;

  private namingSuffix: string;
  private fileSuffix: string;
  constructor(config: Config) {
    this.config = config;
    this.fieldParser = new PrismaFieldParser();
    this.fieldRelationsParser = new PrismaRelationsParser();
    this.schemaParser = new PrismaSchemaParser(this.fieldParser, this.fieldRelationsParser);
    this.dtoGenerator = new NestDtoGenerator({ suffix: config.suffix });
    this.moduleFileGenerator = new NestModuleFileGenerator({ suffix: config.suffix });
    this.serviceGenerator = new NestServiceGenerator({ suffix: config.suffix });
    this.controllerGenerator = new NestControllerGenerator({ suffix: config.suffix, isAdmin: config.isAdmin ?? false });
    this.modulePathResolver = new ModulePathResolver();
    this.appModuleUpdater = new NestAppModuleUpdater();
    this.moduleUpdater = new NestModuleUpdater();
    this.dataProviderGenerator = new DataProviderEndpointGenerator();
    this.namingSuffix = config.suffix.charAt(0).toUpperCase() + config.suffix.slice(1).toLowerCase();
    this.fileSuffix = config.suffix.toLowerCase();
  }

  async generate(): Promise<void> {
    console.log('🚀 Starting API generation...');

    try {
      await this.generateNestStaticFiles();
      this.parseSchema();
      await this.findModules();
      await this.generateFullNestModule();
      this.updateAppModule(this.autoCreatedModules);
      if (this.config.updateDataProvider) {
        this.updateDataProvider();
      }
      console.log('✅ API generation completed successfully!');
    } catch (error) {
      console.error('❌ Error during API generation:', error);
      process.exit(1);
    }
  }

  private async generateNestStaticFiles(): Promise<void> {
    console.log('🔧 Generating Nest Static files...');
    const nestStaticGenerator = new NestStaticGenerator();
    await nestStaticGenerator.generate();
  }

  private parseSchema(): void {
    console.log('📖 Parsing Prisma schema...');

    const schemaContent = fs.readFileSync(this.config.schemaPath, 'utf-8');
    this.schemaParser.load(schemaContent);
    const { models, enums } = this.schemaParser.parse();

    this.models = models;
    this.enums = enums;
    models.forEach((model) => {
      console.log(`📋 Found model with @tg_form(): ${model.name}`);
    });

    console.log(`📊 Found ${this.models.length} models with @tg_form()`);
  }

  private findModulePath(modelName: string): {
    path: string;
    type: GeneratedModuleFolder;
    folderName: string;
  } | null {
    return this.modulePathResolver.findModulePath(modelName, process.cwd());
  }

  private async findModules(): Promise<void> {
    console.log('🔍 Finding corresponding modules...');

    for (const model of this.models) {
      const modelNameLower = toCamelCase(model.name);
      const foundModule = this.findModulePath(model.name);

      if (foundModule) {
        model.modulePath = foundModule.path;
        model.moduleType = foundModule.type;
        console.log(`✅ Found module for ${model.name} in ${foundModule.type}/${foundModule.folderName}`);
        continue;
      }

      // Module not found - prompt user
      console.log(`⚠️ No module found for ${model.name}`);
      console.log(
        `   Tried: ${[
          modelNameLower,
          pluralize(modelNameLower),
          toKebabCase(model.name),
          pluralize(toKebabCase(model.name)),
        ]
          .filter((v, i, a) => a.indexOf(v) === i)
          .join(', ')}`,
      );

      const shouldCreate = await promptUser(`Do you want to create the module directory for ${model.name}? (y/n): `);

      if (shouldCreate) {
        const modulePath = path.join(process.cwd(), 'src', 'features', toKebabCase(model.name));
        fs.mkdirSync(modulePath, { recursive: true });

        // Create the module file
        this.createModuleFile(model, modulePath);

        model.modulePath = modulePath;
        model.moduleType = 'features';
        this.autoCreatedModules.push({
          name: model.name,
          moduleType: 'features',
        });
        console.log(`📁 Created module directory and file: ${modulePath}`);
      } else {
        console.log(`⏭️ Skipping ${model.name}...`);
      }
    }
  }

  private async generateFullNestModule(): Promise<void> {
    console.log('📝 Generating Full Nest Module files...');

    for (const model of this.models) {
      if (!model.modulePath) {
        console.log(`⏭️ Skipping ${model.name} - no module path`);
        continue;
      }

      console.log(`🔧 Generating Full Nest Module files for ${model.name}...`);
      const camelCaseName = toCamelCase(model.name);

      const createDtoContent = tagAutoGenerated(
        this.dtoGenerator.generate({ model, dtoType: 'create', enums: this.enums }),
        model.name,
      );
      const createDtoFileName = `create-${camelCaseName}${this.fileSuffix ? `${this.fileSuffix ? `.${this.fileSuffix}` : ''}` : ''}.dto.ts`;
      const createDtoFilePath = path.join(model.modulePath, createDtoFileName);
      const updateDtoContent = tagAutoGenerated(
        this.dtoGenerator.generate({ model, dtoType: 'update', enums: this.enums }),
        model.name,
      );
      const updateDtoFileName = `update-${camelCaseName}${this.fileSuffix ? `${this.fileSuffix ? `.${this.fileSuffix}` : ''}` : ''}.dto.ts`;
      const updateDtoFilePath = path.join(model.modulePath, updateDtoFileName);

      const passwordFields = model.fields
        .filter((f) => f.name === 'password' || f.tgFormat === 'password')
        .map((f) => f.name);

      const serviceContent = this.serviceGenerator.generate(model, {
        excludeFields: passwordFields,
      });
      const serviceFileName = `${camelCaseName}${this.fileSuffix ? `${this.fileSuffix ? `.${this.fileSuffix}` : ''}` : ''}.service.ts`;
      const serviceFilePath = path.join(model.modulePath, serviceFileName);

      const controllerContent = this.controllerGenerator.generate({ model });
      const controllerFileName = `${camelCaseName}${this.fileSuffix ? `${this.fileSuffix ? `.${this.fileSuffix}` : ''}` : ''}.controller.ts`;
      const controllerFilePath = path.join(model.modulePath, controllerFileName);

      await Promise.all([
        fs.promises.writeFile(createDtoFilePath, createDtoContent),
        fs.promises.writeFile(updateDtoFilePath, updateDtoContent),
        fs.promises.writeFile(serviceFilePath, serviceContent),
        fs.promises.writeFile(controllerFilePath, controllerContent),
      ]);

      formatGeneratedFiles([createDtoFilePath, updateDtoFilePath, serviceFilePath, controllerFilePath], process.cwd());

      // Update module
      this.updateModule(model);

      console.log(`✅ Generated Full Nest Module files for ${model.name}`);
    }
  }

  private createModuleFile(model: PrismaModel, modulePath: string): void {
    const modelNameLower = toCamelCase(model.name);
    const content = this.moduleFileGenerator.generate(model);

    const filePath = path.join(modulePath, `${modelNameLower}.module.ts`);
    fs.writeFileSync(filePath, content);
    console.log(`📄 Created module file: ${filePath}`);
  }

  private updateAppModule(mods?: { name: string; moduleType: GeneratedModuleFolder }[]): void {
    if (!mods || mods.length === 0) return;
    console.log('🔄 Updating AppModule with auto-created modules...');

    const appModulePath = path.join(process.cwd(), 'src', 'app.module.ts');
    let appModuleContent = fs.readFileSync(appModulePath, 'utf-8');

    // Step 1: Parse and update import statements
    appModuleContent = this.appModuleUpdater.updateImportStatements(appModuleContent, mods);

    // Step 2: Parse and update imports array
    appModuleContent = this.appModuleUpdater.updateImportsArray(appModuleContent, mods);

    fs.writeFileSync(appModulePath, appModuleContent);

    // Format the file with Prettier
    formatGeneratedFile(appModulePath, process.cwd());

    console.log('✅ Updated AppModule with auto-created modules');
  }

  private updateModule(model: PrismaModel): void {
    if (!model.modulePath) {
      console.log(`⚠️ No module path for ${model.name}`);
      return;
    }

    const moduleFileName = this.modulePathResolver.getModuleFileName(model.modulePath);
    if (!moduleFileName) {
      console.log(`⚠️ Module file not found in: ${model.modulePath}`);
      console.log(`📄 Creating module file for ${model.name}...`);
      this.createModuleFile(model, model.modulePath);
      // Track this as auto-created since we just created it
      this.autoCreatedModules.push({
        name: model.name,
        moduleType: model.moduleType,
      });
      return;
    }

    const modulePath = path.join(model.modulePath, moduleFileName);
    let moduleContent = fs.readFileSync(modulePath, 'utf-8');
    const modelNameLower = toCamelCase(model.name);
    const controllerClassName = `${model.name}${this.namingSuffix}Controller`;
    const serviceClassName = `${model.name}${this.namingSuffix}Service`;
    const { controllerImport, serviceImport } = this.moduleUpdater.generateModuleImportStatements(
      model.name,
      modelNameLower,
      this.namingSuffix,
      this.fileSuffix,
    );

    // Add imports if needed
    if (!moduleContent.includes(controllerClassName)) {
      moduleContent = this.moduleUpdater.addImportsToModule(moduleContent, [controllerImport, serviceImport]);
    }

    // Add to controllers array if not present
    moduleContent = this.moduleUpdater.addToArrayInModule(moduleContent, 'controllers', [controllerClassName]);

    // Add to providers array if not present
    moduleContent = this.moduleUpdater.addToArrayInModule(moduleContent, 'providers', [serviceClassName]);

    fs.writeFileSync(modulePath, moduleContent);
    console.log(`✅ Updated module: ${modulePath}`);
  }

  private updateDataProvider(): void {
    console.log('🔄 Updating dataProvider endpoint map...');

    const dataProviderPath = path.join(process.cwd(), 'src', 'dashboard', 'src', 'providers', 'dataProvider.ts');
    let content = fs.readFileSync(dataProviderPath, 'utf-8');

    // Find the endpointMap object
    const endpointMapRegex = /const endpointMap:\s*Record<string,\s*string>\s*=\s*\{([\s\S]*?)\n\s*\};/;
    const match = content.match(endpointMapRegex);

    if (!match) {
      console.log('⚠️ Could not find endpointMap in dataProvider');
      return;
    }

    const existingContent = match[1];

    // Extract custom endpoints
    const customEndpoints = this.dataProviderGenerator.extractCustomEndpoints(existingContent ?? '');

    // Generate new API mappings

    const autoGeneratedMappings = this.dataProviderGenerator.generateEndpointMappings(
      this.models,
      getResourceName,
      (modelName) => this.controllerGenerator.getApiEndpoint(modelName),
    );

    // Build the new endpoint map
    const updatedEndpointMap = this.dataProviderGenerator.buildEndpointMap(autoGeneratedMappings, customEndpoints);

    content = content.replace(endpointMapRegex, updatedEndpointMap);
    fs.writeFileSync(dataProviderPath, content);
    console.log('✅ Updated dataProvider endpoint map');
  }
}
