import * as fs from 'fs';
import { tagAutoGenerated } from './src/generator/utils/auto-text';
import { formatGeneratedFile } from './src/io/utils/format-files';
import { DtoGenerator } from './generate-dtos';
import type { Config} from '@tg-scripts/types';

const config: Config = {
  schemaPath: 'prisma/schema.prisma',
  dashboardPath: 'src/dashboard/src',
  dtosPath: 'src/dtos/generated',
  suffix: 'Test',
};

// Mock all dependencies
jest.mock('fs');
jest.mock('./src/generator/utils/auto-text');
jest.mock('./src/file-operations');
jest.mock('./src/io/utils/format-files');

// Mock console methods to avoid cluttering test output
const originalConsole = global.console;
beforeAll(() => {
  global.console = {
    ...originalConsole,
    log: jest.fn(),
    error: jest.fn(),
  };
});

afterAll(() => {
  global.console = originalConsole;
});

describe('TgDtoGenerator', () => {
  let generator: DtoGenerator;
  let mockFs: jest.Mocked<typeof fs>;
  let mockTagAutoGenerated: jest.MockedFunction<typeof tagAutoGenerated>;
  let mockFormatGeneratedFile: jest.MockedFunction<typeof formatGeneratedFile>;
  let mockProcessCwd: jest.SpyInstance;
  let mockProcessExit: jest.SpyInstance;

  // Note: mockModels and mockEnums removed - tests now use real parser with schema content

  beforeEach(() => {
    jest.clearAllMocks();

    // Setup mocks
    mockFs = fs as jest.Mocked<typeof fs>;
    mockTagAutoGenerated = tagAutoGenerated as jest.MockedFunction<typeof tagAutoGenerated>;
    mockFormatGeneratedFile = formatGeneratedFile as jest.MockedFunction<typeof formatGeneratedFile>;

    // Mock process.cwd()
    mockProcessCwd = jest.spyOn(process, 'cwd').mockReturnValue('/mock/project/root');

    // Mock process.exit()
    mockProcessExit = jest.spyOn(process, 'exit').mockImplementation((code?: number) => {
      throw new Error(`Process exit called with code: ${code}`);
    });

    // Default implementations
    mockFs.existsSync.mockReturnValue(false);
    mockFs.rmSync.mockImplementation(() => {});
    mockFs.mkdirSync.mockReturnValue(undefined);
    // Provide real schema content that the parser can parse
    const defaultSchema = `
// @tg_form()
model User {
  id String @id @default(uuid())
  email String @unique
  firstName String
  lastName String
}

// @tg_form()
model Post {
  id String @id @default(uuid())
  title String
  content String?
}
`;
    mockFs.readFileSync.mockImplementation((filePath: string) => {
      if (filePath.toString().includes('schema.prisma')) {
        return defaultSchema;
      }
      return '';
    });
    mockFs.writeFileSync.mockImplementation(() => {});

    mockTagAutoGenerated.mockImplementation((text) => `/* AUTO-GENERATED */\n${text}`);
    mockFormatGeneratedFile.mockImplementation(() => {});

    generator = new DtoGenerator(config);
  });

  afterEach(() => {
    mockProcessCwd.mockRestore();
    mockProcessExit.mockRestore();
  });

  describe('Constructor', () => {

    it('should set schemaPath to prisma/schema.prisma', () => {
      const gen = new DtoGenerator(config);

      gen.generate();

      expect(mockFs.readFileSync).toHaveBeenCalledWith('prisma/schema.prisma', 'utf-8');
    });

    it('should set outputDir to src/dtos/generated', () => {
      const gen = new DtoGenerator(config);

      gen.generate();

      expect(mockFs.existsSync).toHaveBeenCalledWith('src/dtos/generated');
      expect(mockFs.mkdirSync).toHaveBeenCalledWith('src/dtos/generated', expect.objectContaining({ recursive: true }));
    });
  });

  describe('generate', () => {
    it('should complete full generation process successfully', () => {
      generator.generate();

      expect(mockFs.existsSync).toHaveBeenCalled();
      expect(mockFs.readFileSync).toHaveBeenCalled();
      // Check that DTO files were generated (2 models = 2 DTO files + 1 index)
      const dtoFileCalls = mockFs.writeFileSync.mock.calls.filter((call) =>
        call[0].toString().includes('-response.dto.ts'),
      );
      expect(dtoFileCalls.length).toBe(2);
      expect(mockFs.writeFileSync).toHaveBeenCalled();
      expect(mockFormatGeneratedFile).toHaveBeenCalled();
      expect(console.log).toHaveBeenCalledWith('✅ DTO generation completed successfully!');
    });

    it('should call all steps in correct order', () => {
      const order: string[] = [];

      mockFs.existsSync.mockImplementation(() => {
        order.push('existsSync');
        return false;
      });
      mockFs.rmSync.mockImplementation(() => {
        order.push('rmSync');
      });
      mockFs.mkdirSync.mockImplementation(() => {
        order.push('mkdirSync');
        return undefined;
      });
      mockFs.readFileSync.mockImplementation(() => {
        order.push('readFileSync');
        // Return actual schema content so parser can find models
        return `
// @tg_form()
model User {
  id String @id @default(uuid())
  email String @unique
  firstName String
  lastName String
}

// @tg_form()
model Post {
  id String @id @default(uuid())
  title String
  content String?
}
`;
      });
      // Schema parsing and DTO generation happens automatically with real parser and generator
      mockFs.writeFileSync.mockImplementation(() => {
        order.push('writeFileSync');
      });
      mockFormatGeneratedFile.mockImplementation(() => order.push('formatGeneratedFile'));

      generator.generate();

      // Note: Schema parsing and DTO generation happens automatically with real implementations
      // The order will be: existsSync, mkdirSync, readFileSync, then DTO generation and file writing
      expect(order).toContain('existsSync');
      expect(order).toContain('mkdirSync');
      expect(order).toContain('readFileSync');
      // DTO files are written
      expect(order.filter((o) => o === 'writeFileSync').length).toBeGreaterThanOrEqual(3); // At least 2 DTOs + index
    });

    it('should exit with code 1 on error', () => {
      const error = new Error('Test error');
      mockFs.readFileSync.mockImplementation(() => {
        throw error;
      });

      expect(() => generator.generate()).toThrow('Process exit called with code: 1');
      expect(console.error).toHaveBeenCalledWith('❌ Error during DTO generation:', error);
      expect(mockProcessExit).toHaveBeenCalledWith(1);
    });

    it('should handle errors during setupOutputDirectory', () => {
      const error = new Error('Directory error');
      mockFs.existsSync.mockImplementation(() => {
        throw error;
      });

      expect(() => generator.generate()).toThrow('Process exit called with code: 1');
      expect(console.error).toHaveBeenCalled();
    });

    it('should handle errors during parseSchema', () => {
      const error = new Error('Parse error');
      mockFs.readFileSync.mockImplementation(() => {
        throw error;
      });

      expect(() => generator.generate()).toThrow('Process exit called with code: 1');
      expect(console.error).toHaveBeenCalled();
    });

    it('should handle errors during generateDtos', () => {
      // Error would come from DTO generation itself, which uses real NestDtoGenerator
      // We can't easily mock internal errors, so this test verifies error handling path exists
      const error = new Error('Write error');
      let callCount = 0;
      mockFs.writeFileSync.mockImplementation(() => {
        callCount++;
        if (callCount === 1) {
          // First DTO file write fails
          throw error;
        }
      });

      expect(() => generator.generate()).toThrow('Process exit called with code: 1');
      expect(console.error).toHaveBeenCalled();
    });

    it('should handle errors during generateIndexFile', () => {
      const error = new Error('Index error');
      mockFs.writeFileSync.mockImplementation((filePath: string) => {
        if (filePath.includes('index.ts')) {
          throw error;
        }
      });

      expect(() => generator.generate()).toThrow('Process exit called with code: 1');
      expect(console.error).toHaveBeenCalled();
    });

    it('should log progress messages', () => {
      generator.generate();

      expect(console.log).toHaveBeenCalledWith('🚀 Starting DTO generation...');
      expect(console.log).toHaveBeenCalledWith('📁 Setting up output directory...');
      expect(console.log).toHaveBeenCalledWith('📖 Parsing Prisma schema...');
      expect(console.log).toHaveBeenCalledWith('📝 Generating DTO files...');
      expect(console.log).toHaveBeenCalledWith('✅ Generated user-response.dto.ts');
      expect(console.log).toHaveBeenCalledWith('✅ Generated post-response.dto.ts');
      expect(console.log).toHaveBeenCalledWith('📄 Generating index file...');
      expect(console.log).toHaveBeenCalledWith('✅ Generated index.ts');
      expect(console.log).toHaveBeenCalledWith('🎨 Formatting generated files...');
      expect(console.log).toHaveBeenCalledWith('✅ DTO generation completed successfully!');
    });
  });

  describe('setupOutputDirectory', () => {
    it('should remove existing directory if it exists', () => {
      mockFs.existsSync.mockReturnValue(true);

      generator.generate();

      expect(mockFs.existsSync).toHaveBeenCalledWith('src/dtos/generated');
      expect(mockFs.rmSync).toHaveBeenCalledWith('src/dtos/generated', {
        recursive: true,
        force: true,
      });
    });

    it('should create directory if it does not exist', () => {
      mockFs.existsSync.mockReturnValue(false);

      generator.generate();

      expect(mockFs.rmSync).not.toHaveBeenCalled();
      expect(mockFs.mkdirSync).toHaveBeenCalledWith('src/dtos/generated', expect.objectContaining({ recursive: true }));
    });

    it('should create directory even if it was removed', () => {
      mockFs.existsSync.mockReturnValue(true);

      generator.generate();

      expect(mockFs.rmSync).toHaveBeenCalled();
      expect(mockFs.mkdirSync).toHaveBeenCalledWith('src/dtos/generated', expect.objectContaining({ recursive: true }));
    });

    it('should handle errors when removing directory', () => {
      const error = new Error('Permission denied');
      mockFs.existsSync.mockReturnValue(true);
      mockFs.rmSync.mockImplementation(() => {
        throw error;
      });

      expect(() => generator.generate()).toThrow('Process exit called with code: 1');
    });

    it('should handle errors when creating directory', () => {
      const error = new Error('Cannot create directory');
      mockFs.existsSync.mockReturnValue(false);
      mockFs.mkdirSync.mockImplementation(() => {
        throw error;
      });

      expect(() => generator.generate()).toThrow('Process exit called with code: 1');
    });
  });

  describe('parseSchema', () => {
    it('should read schema file with correct path', () => {
      generator.generate();

      expect(mockFs.readFileSync).toHaveBeenCalledWith(
        'prisma/schema.prisma',
        'utf-8',
      );
    });

    it('should parse schema content', () => {
      const schemaContent = 'model User { id String @id }';
      mockFs.readFileSync.mockReturnValue(schemaContent);

      generator.generate();

      expect(mockFs.readFileSync).toHaveBeenCalled();
    });

    it('should store parsed models and enums', () => {
      generator.generate();

      // Verify that models and enums were parsed and stored
      // Check that DTO files were written
      const dtoFileCalls = mockFs.writeFileSync.mock.calls.filter((call) =>
        call[0].toString().includes('-response.dto.ts'),
      );
      expect(dtoFileCalls.length).toBeGreaterThan(0);

      // Verify the generated content contains expected structure
      const dtoContent = dtoFileCalls[0]?.[1] as string;
      expect(dtoContent).toContain('export class');
      expect(dtoContent).toContain('ResponseDto');
    });

    it('should create availableModels set from parsed models', () => {
      generator.generate();

      // Verify that DTOs were generated with correct models
      const dtoFileCalls = mockFs.writeFileSync.mock.calls.filter((call) =>
        call[0].toString().includes('-response.dto.ts'),
      );
      expect(dtoFileCalls.length).toBe(2);

      // Check that the generated DTOs contain expected model names
      const userDtoContent = dtoFileCalls.find((call) =>
        call[0].toString().includes('user-response.dto.ts'),
      )?.[1] as string;
      const postDtoContent = dtoFileCalls.find((call) =>
        call[0].toString().includes('post-response.dto.ts'),
      )?.[1] as string;

      expect(userDtoContent).toContain('UserResponseDto');
      expect(postDtoContent).toContain('PostResponseDto');
    });

    it('should log each found model', () => {
      generator.generate();

      expect(console.log).toHaveBeenCalledWith(expect.stringContaining('User'));
      expect(console.log).toHaveBeenCalledWith(expect.stringContaining('Post'));
    });

    it('should log total model count', () => {
      generator.generate();

      expect(console.log).toHaveBeenCalledWith('📊 Found 2 models in schema');
    });

    it('should handle empty models array', () => {
      // Override schema with no models that have @tg_form()
      const testSchema = `
model User {
  id String @id
}
`;
      mockFs.readFileSync.mockImplementation((filePath: string) => {
        if (filePath.toString().includes('schema.prisma')) {
          return testSchema;
        }
        return '';
      });

      generator.generate();

      // Verify no DTO files were written (only index file)
      const dtoFileCalls = mockFs.writeFileSync.mock.calls.filter((call) =>
        call[0].toString().includes('-response.dto.ts'),
      );
      expect(dtoFileCalls.length).toBe(0);
      expect(mockFs.writeFileSync).toHaveBeenCalledWith(
        expect.stringContaining('index.ts'),
        expect.stringContaining('/* AUTO-GENERATED */'),
      );
    });

    it('should handle errors reading schema file', () => {
      const error = new Error('File not found');
      mockFs.readFileSync.mockImplementation(() => {
        throw error;
      });

      expect(() => generator.generate()).toThrow('Process exit called with code: 1');
      expect(console.error).toHaveBeenCalledWith('❌ Error during DTO generation:', error);
    });
  });

  describe('generateDtos', () => {
    it('should generate DTO file for each model', () => {
      generator.generate();

      const dtoFileCalls = mockFs.writeFileSync.mock.calls.filter((call) =>
        call[0].toString().includes('-response.dto.ts'),
      );
      expect(dtoFileCalls.length).toBe(2);

      // Verify the generated DTOs contain expected structure
      const userDtoCall = dtoFileCalls.find((call) => call[0].toString().includes('user-response.dto.ts'));
      const postDtoCall = dtoFileCalls.find((call) => call[0].toString().includes('post-response.dto.ts'));

      expect(userDtoCall).toBeDefined();
      expect(postDtoCall).toBeDefined();

      const userDtoContent = userDtoCall?.[1] as string;
      const postDtoContent = postDtoCall?.[1] as string;

      expect(userDtoContent).toContain('UserResponseDto');
      expect(userDtoContent).toContain('@ApiProperty');
      expect(postDtoContent).toContain('PostResponseDto');
      expect(postDtoContent).toContain('@ApiProperty');
    });

    it('should generate file names in lowercase', () => {
      // Override schema with mixed case model names
      const testSchema = `
// @tg_form()
model UserProfile {
  id String @id
}

// @tg_form()
model PostComment {
  id String @id
}
`;
      mockFs.readFileSync.mockImplementation((filePath: string) => {
        if (filePath.toString().includes('schema.prisma')) {
          return testSchema;
        }
        return '';
      });

      generator.generate();

      expect(mockFs.writeFileSync).toHaveBeenCalledWith(
        expect.stringContaining('userprofile-response.dto.ts'),
        expect.any(String),
      );
      expect(mockFs.writeFileSync).toHaveBeenCalledWith(
        expect.stringContaining('postcomment-response.dto.ts'),
        expect.any(String),
      );
    });

    it('should tag generated content with auto-generated header', () => {
      generator.generate();

      const dtoFileCalls = mockFs.writeFileSync.mock.calls.filter((call) =>
        call[0].toString().includes('user-response.dto.ts'),
      );
      expect(dtoFileCalls.length).toBe(1);

      // Verify tagAutoGenerated was called
      expect(mockTagAutoGenerated).toHaveBeenCalled();
      const taggedCall = mockTagAutoGenerated.mock.calls.find(
        (call) => call[1] === 'User' && call[2] === 'DTO Generator',
      );
      expect(taggedCall).toBeDefined();
    });

    it('should format each generated file', () => {
      generator.generate();

      expect(mockFormatGeneratedFile).toHaveBeenCalledWith(
        expect.stringContaining('user-response.dto.ts'),
        expect.any(String),
      );
      expect(mockFormatGeneratedFile).toHaveBeenCalledWith(
        expect.stringContaining('post-response.dto.ts'),
        expect.any(String),
      );
    });

    it('should log generation for each model', () => {
      generator.generate();

      expect(console.log).toHaveBeenCalledWith('✅ Generated user-response.dto.ts');
      expect(console.log).toHaveBeenCalledWith('✅ Generated post-response.dto.ts');
    });

    it('should handle errors during DTO content generation', () => {
      // Error would come from DTO generation itself, which uses real NestDtoGenerator
      // We can't easily mock internal errors, so this test verifies error handling path exists
      const error = new Error('Generation failed');
      let callCount = 0;
      mockFs.writeFileSync.mockImplementation(() => {
        callCount++;
        if (callCount === 1) {
          // First DTO file write fails
          throw error;
        }
      });

      expect(() => generator.generate()).toThrow('Process exit called with code: 1');
    });

    it('should handle errors during file writing', () => {
      const error = new Error('Write failed');
      let callCount = 0;
      mockFs.writeFileSync.mockImplementation(() => {
        callCount++;
        if (callCount === 1) {
          throw error;
        }
      });

      expect(() => generator.generate()).toThrow('Process exit called with code: 1');
    });

    it('should handle errors during file formatting', () => {
      const error = new Error('Format failed');
      mockFormatGeneratedFile.mockImplementation(() => {
        throw error;
      });

      expect(() => generator.generate()).toThrow('Process exit called with code: 1');
    });

    it('should generate DTOs in order of models array', () => {
      // Override schema with models in specific order
      const testSchema = `
// @tg_form()
model A {
  id String @id
}

// @tg_form()
model B {
  id String @id
}

// @tg_form()
model C {
  id String @id
}
`;
      mockFs.readFileSync.mockImplementation((filePath: string) => {
        if (filePath.toString().includes('schema.prisma')) {
          return testSchema;
        }
        return '';
      });

      generator.generate();

      // Verify DTOs were generated in correct order by checking file write order
      const dtoFileCalls = mockFs.writeFileSync.mock.calls.filter((call) =>
        call[0].toString().includes('-response.dto.ts'),
      );
      expect(dtoFileCalls.length).toBe(3);

      // Check that DTOs contain correct model names
      const aDtoContent = dtoFileCalls.find((call) => call[0].toString().includes('a-response.dto.ts'))?.[1] as string;
      const bDtoContent = dtoFileCalls.find((call) => call[0].toString().includes('b-response.dto.ts'))?.[1] as string;
      const cDtoContent = dtoFileCalls.find((call) => call[0].toString().includes('c-response.dto.ts'))?.[1] as string;

      expect(aDtoContent).toContain('AResponseDto');
      expect(bDtoContent).toContain('BResponseDto');
      expect(cDtoContent).toContain('CResponseDto');
    });

    it('should pass correct enums map to each DTO generation', () => {
      // Override schema with enum definitions
      const testSchema = `
enum Status {
  ACTIVE
}

enum Type {
  TYPE_A
  TYPE_B
}

// @tg_form()
model User {
  id String @id
  status Status
  type Type
}
`;
      mockFs.readFileSync.mockImplementation((filePath: string) => {
        if (filePath.toString().includes('schema.prisma')) {
          return testSchema;
        }
        return '';
      });

      generator.generate();

      // Verify enums were used in generated DTOs by checking import statements
      const dtoFileCalls = mockFs.writeFileSync.mock.calls.filter((call) =>
        call[0].toString().includes('-response.dto.ts'),
      );
      expect(dtoFileCalls.length).toBe(1);

      const dtoContent = dtoFileCalls[0]?.[1] as string;
      // Check that enum imports or types are present in the generated DTO
      expect(dtoContent).toContain('Status');
      expect(dtoContent).toContain('Type');
    });

    it('should pass correct availableModels set to each DTO generation', () => {
      generator.generate();

      // Verify DTOs were generated for both models
      const dtoFileCalls = mockFs.writeFileSync.mock.calls.filter((call) =>
        call[0].toString().includes('-response.dto.ts'),
      );
      expect(dtoFileCalls.length).toBe(2);

      // Both DTOs should exist
      const userDtoContent = dtoFileCalls.find((call) =>
        call[0].toString().includes('user-response.dto.ts'),
      )?.[1] as string;
      const postDtoContent = dtoFileCalls.find((call) =>
        call[0].toString().includes('post-response.dto.ts'),
      )?.[1] as string;

      expect(userDtoContent).toContain('UserResponseDto');
      expect(postDtoContent).toContain('PostResponseDto');
    });

    it('should handle models with no fields', () => {
      // Override schema with empty model
      const testSchema = `
// @tg_form()
model EmptyModel {
}
`;
      mockFs.readFileSync.mockImplementation((filePath: string) => {
        if (filePath.toString().includes('schema.prisma')) {
          return testSchema;
        }
        return '';
      });

      generator.generate();

      // Verify DTO file was generated
      const dtoFileCalls = mockFs.writeFileSync.mock.calls.filter((call) =>
        call[0].toString().includes('emptymodel-response.dto.ts'),
      );
      expect(dtoFileCalls.length).toBe(1);

      const dtoContent = dtoFileCalls[0]?.[1] as string;
      expect(dtoContent).toContain('EmptyModelResponseDto');
    });
  });

  describe('generateIndexFile', () => {
    it('should generate index file with exports for all models', () => {
      generator.generate();

      expect(mockFs.writeFileSync).toHaveBeenCalledWith(
        expect.stringContaining('index.ts'),
        expect.any(String),
      );

      const indexCall = mockFs.writeFileSync.mock.calls.find((call) => call[0].toString().includes('index.ts'));
      const indexContent = indexCall?.[1] as string;

      expect(indexContent).toContain("export * from './user-response.dto';");
      expect(indexContent).toContain("export * from './post-response.dto';");
    });

    it('should tag index file with auto-generated header', () => {
      generator.generate();

      expect(mockTagAutoGenerated).toHaveBeenCalledWith(
        expect.stringContaining("export * from './user-response.dto'"),
        undefined,
        'DTO Generator',
      );
    });

    it('should format index file', () => {
      generator.generate();

      expect(mockFormatGeneratedFile).toHaveBeenCalledWith(
        expect.stringContaining('index.ts'),
        expect.any(String),
      );
    });

    it('should generate empty index when no models', () => {
      // Override schema with no models that have @tg_form()
      const testSchema = `
model User {
  id String @id
}
`;
      mockFs.readFileSync.mockImplementation((filePath: string) => {
        if (filePath.toString().includes('schema.prisma')) {
          return testSchema;
        }
        return '';
      });

      generator.generate();

      const indexCall = mockFs.writeFileSync.mock.calls.find((call) => call[0].toString().includes('index.ts'));
      const indexContent = indexCall?.[1] as string;

      expect(indexContent).not.toContain("export * from './");
    });

    it('should generate exports in model order', () => {
      // Override schema with models in specific order
      const testSchema = `
// @tg_form()
model Alpha {
  id String @id
}

// @tg_form()
model Beta {
  id String @id
}

// @tg_form()
model Gamma {
  id String @id
}
`;
      mockFs.readFileSync.mockImplementation((filePath: string) => {
        if (filePath.toString().includes('schema.prisma')) {
          return testSchema;
        }
        return '';
      });

      generator.generate();

      const indexCall = mockFs.writeFileSync.mock.calls.find((call) => call[0].toString().includes('index.ts'));
      const indexContent = indexCall?.[1] as string;

      const alphaIndex = indexContent.indexOf("export * from './alpha-response.dto'");
      const betaIndex = indexContent.indexOf("export * from './beta-response.dto'");
      const gammaIndex = indexContent.indexOf("export * from './gamma-response.dto'");

      expect(alphaIndex).toBeLessThan(betaIndex);
      expect(betaIndex).toBeLessThan(gammaIndex);
    });

    it('should use lowercase model names in export paths', () => {
      // Override schema with mixed case model name
      const testSchema = `
// @tg_form()
model UserProfile {
  id String @id
}
`;
      mockFs.readFileSync.mockImplementation((filePath: string) => {
        if (filePath.toString().includes('schema.prisma')) {
          return testSchema;
        }
        return '';
      });

      generator.generate();

      const indexCall = mockFs.writeFileSync.mock.calls.find((call) => call[0].toString().includes('index.ts'));
      const indexContent = indexCall?.[1] as string;

      expect(indexContent).toContain("export * from './userprofile-response.dto';");
      expect(indexContent).not.toContain('UserProfile');
    });

    it('should handle errors writing index file', () => {
      const error = new Error('Index write failed');
      let callCount = 0;
      mockFs.writeFileSync.mockImplementation((filePath: string) => {
        if (filePath.toString().includes('index.ts')) {
          callCount++;
          if (callCount === 1) {
            throw error;
          }
        }
      });

      expect(() => generator.generate()).toThrow('Process exit called with code: 1');
    });

    it('should handle errors formatting index file', () => {
      const error = new Error('Index format failed');
      let formatCount = 0;
      mockFormatGeneratedFile.mockImplementation((filePath: string) => {
        if (filePath.toString().includes('index.ts')) {
          formatCount++;
          if (formatCount === 1) {
            throw error;
          }
        }
      });

      expect(() => generator.generate()).toThrow('Process exit called with code: 1');
    });
  });

  describe('formatFiles', () => {
    it('should complete without errors', () => {
      generator.generate();

      // formatFiles method currently doesn't do anything explicit,
      // but we verify the method executes without errors
      expect(console.log).toHaveBeenCalledWith('🎨 Formatting generated files...');
    });
  });

  describe('Edge Cases and Error Scenarios', () => {
    it('should handle models with special characters in names', () => {
      // Override schema with model containing underscores
      const testSchema = `
// @tg_form()
model Model_With_Underscores {
  id String @id
}
`;
      mockFs.readFileSync.mockImplementation((filePath: string) => {
        if (filePath.toString().includes('schema.prisma')) {
          return testSchema;
        }
        return '';
      });

      generator.generate();

      expect(mockFs.writeFileSync).toHaveBeenCalledWith(
        expect.stringContaining('model_with_underscores-response.dto.ts'),
        expect.any(String),
      );
    });

    it('should handle very large number of models', () => {
      // Override schema with many models
      const models = Array.from({ length: 100 }, (_, i) => {
        return `// @tg_form()
model Model${i} {
  id String @id
}`;
      }).join('\n\n');
      const testSchema = models;

      mockFs.readFileSync.mockImplementation((filePath: string) => {
        if (filePath.toString().includes('schema.prisma')) {
          return testSchema;
        }
        return '';
      });

      generator.generate();

      // Verify 100 DTO files were generated plus 1 index file
      const dtoFileCalls = mockFs.writeFileSync.mock.calls.filter((call) =>
        call[0].toString().includes('-response.dto.ts'),
      );
      expect(dtoFileCalls.length).toBe(100);
      expect(mockFs.writeFileSync).toHaveBeenCalledTimes(101); // 100 DTOs + 1 index
    });

    it('should handle models with complex enum dependencies', () => {
      // Override schema with models and enums
      const testSchema = `
enum EnumA {
  VALUE_A1
  VALUE_A2
}

enum EnumB {
  VALUE_B1
  VALUE_B2
  VALUE_B3
}

enum EnumC {
  VALUE_C1
}

// @tg_form()
model ComplexModel {
  id String @id
  enumField EnumA
  enumFieldB EnumB
}
`;
      mockFs.readFileSync.mockImplementation((filePath: string) => {
        if (filePath.toString().includes('schema.prisma')) {
          return testSchema;
        }
        return '';
      });

      generator.generate();

      // Verify DTO was generated for ComplexModel
      const dtoFileCalls = mockFs.writeFileSync.mock.calls.filter((call) =>
        call[0].toString().includes('complexmodel-response.dto.ts'),
      );
      expect(dtoFileCalls.length).toBe(1);

      const dtoContent = dtoFileCalls[0]?.[1] as string;
      expect(dtoContent).toContain('ComplexModelResponseDto');
      // Verify enums were used in generated DTO
      expect(dtoContent).toContain('EnumA');
      expect(dtoContent).toContain('EnumB');
    });

    it('should handle concurrent execution scenarios', () => {
      // Simulate rapid successive calls
      const gen1 = new DtoGenerator(config);
      const gen2 = new DtoGenerator(config);

      gen1.generate();
      gen2.generate();

      // Both should complete without interference
      // Verify DTO files were written for both generators
      const dtoFileCalls = mockFs.writeFileSync.mock.calls.filter((call) =>
        call[0].toString().includes('-response.dto.ts'),
      );
      expect(dtoFileCalls.length).toBeGreaterThanOrEqual(2); // At least 2 DTOs (could be more if both generators ran)
    });

    it('should handle filesystem permission errors', () => {
      const error = new Error('EACCES: permission denied');
      mockFs.mkdirSync.mockImplementation(() => {
        throw error;
      });

      expect(() => generator.generate()).toThrow('Process exit called with code: 1');
      expect(console.error).toHaveBeenCalled();
    });

    it('should handle disk full errors', () => {
      const error = new Error('ENOSPC: no space left on device');
      mockFs.writeFileSync.mockImplementation(() => {
        throw error;
      });

      expect(() => generator.generate()).toThrow('Process exit called with code: 1');
    });

    it('should handle invalid schema format gracefully', () => {
      // Invalid schema will be parsed but won't produce models (no @tg_form())
      const invalidSchema = 'invalid schema content';
      mockFs.readFileSync.mockImplementation((filePath: string) => {
        if (filePath.toString().includes('schema.prisma')) {
          return invalidSchema;
        }
        return '';
      });

      // The parser handles invalid schema gracefully - no models found, no error thrown
      generator.generate();

      // Should complete without error, but no DTOs generated
      const dtoFileCalls = mockFs.writeFileSync.mock.calls.filter((call) =>
        call[0].toString().includes('-response.dto.ts'),
      );
      expect(dtoFileCalls.length).toBe(0);
    });

    it('should handle null or undefined from dependencies', () => {
      // Test that the generator handles errors gracefully
      const error = new Error('Parse error');
      mockFs.readFileSync.mockImplementation(() => {
        throw error;
      });

      expect(() => generator.generate()).toThrow('Process exit called with code: 1');
      expect(console.error).toHaveBeenCalled();
    });

    it('should handle empty schema file', () => {
      mockFs.readFileSync.mockImplementation((filePath: string) => {
        if (filePath.toString().includes('schema.prisma')) {
          return '';
        }
        return '';
      });

      generator.generate();

      expect(mockFs.readFileSync).toHaveBeenCalled();
      const dtoFileCalls = mockFs.writeFileSync.mock.calls.filter((call) =>
        call[0].toString().includes('-response.dto.ts'),
      );
      expect(dtoFileCalls.length).toBe(0);
    });

    it('should handle schema with only comments', () => {
      mockFs.readFileSync.mockImplementation((filePath: string) => {
        if (filePath.toString().includes('schema.prisma')) {
          return '// Just a comment\n// Another comment';
        }
        return '';
      });

      generator.generate();

      expect(mockFs.readFileSync).toHaveBeenCalled();
      const dtoFileCalls = mockFs.writeFileSync.mock.calls.filter((call) =>
        call[0].toString().includes('-response.dto.ts'),
      );
      expect(dtoFileCalls.length).toBe(0);
    });
  });

  describe('Integration Scenarios', () => {
    it('should handle complete workflow with real structure', () => {
      // Override schema content for this specific test
      const testSchema = `
// @tg_form()
model User {
  id String @id
  email String @unique
}
`;
      mockFs.readFileSync.mockImplementation((filePath: string) => {
        if (filePath.toString().includes('schema.prisma')) {
          return testSchema;
        }
        return '';
      });

      generator.generate();

      // Verify all steps executed
      expect(mockFs.existsSync).toHaveBeenCalled();
      expect(mockFs.readFileSync).toHaveBeenCalled();

      // Verify DTO was generated
      const dtoFileCalls = mockFs.writeFileSync.mock.calls.filter((call) =>
        call[0].toString().includes('-response.dto.ts'),
      );
      expect(dtoFileCalls.length).toBe(1);

      const dtoContent = dtoFileCalls[0]?.[1] as string;
      expect(dtoContent).toContain('UserResponseDto');
      expect(dtoContent).toContain('@ApiProperty');

      expect(mockTagAutoGenerated).toHaveBeenCalled();
      expect(mockFs.writeFileSync).toHaveBeenCalledTimes(2); // 1 DTO + 1 index
      expect(mockFormatGeneratedFile).toHaveBeenCalledTimes(2);
    });

    it('should maintain correct file paths throughout execution', () => {
      const customGen = new DtoGenerator(config);
      customGen.generate();

      // Config uses relative paths
      expect(mockFs.readFileSync).toHaveBeenCalledWith('prisma/schema.prisma', 'utf-8');
      expect(mockFs.existsSync).toHaveBeenCalledWith('src/dtos/generated');
      expect(mockFs.writeFileSync).toHaveBeenCalledWith(
        expect.stringContaining('user-response.dto.ts'),
        expect.any(String),
      );
    });
  });

  describe('Type Safety and Data Integrity', () => {
    it('should preserve model data structure', () => {
      // Override schema with model containing all field types
      const testSchema = `
enum Status {
  ACTIVE
  INACTIVE
}

// @tg_form()
model CompleteModel {
  id String @id
  optionalField String?
  arrayField String[]
  status Status
}
`;
      mockFs.readFileSync.mockImplementation((filePath: string) => {
        if (filePath.toString().includes('schema.prisma')) {
          return testSchema;
        }
        return '';
      });

      generator.generate();

      // Verify DTO was generated with all field types
      const dtoFileCalls = mockFs.writeFileSync.mock.calls.filter((call) =>
        call[0].toString().includes('completemodel-response.dto.ts'),
      );
      expect(dtoFileCalls.length).toBe(1);

      const dtoContent = dtoFileCalls[0]?.[1] as string;
      expect(dtoContent).toContain('CompleteModelResponseDto');
      expect(dtoContent).toContain('id');
      expect(dtoContent).toContain('optionalField');
      expect(dtoContent).toContain('arrayField');
      expect(dtoContent).toContain('status');
      expect(dtoContent).toContain('Status');
    });

    it('should handle enum map correctly', () => {
      // Override schema with enum
      const testSchema = `
enum Status {
  ACTIVE
  INACTIVE
}

// @tg_form()
model EnumModel {
  id String @id
  status Status
}
`;
      mockFs.readFileSync.mockImplementation((filePath: string) => {
        if (filePath.toString().includes('schema.prisma')) {
          return testSchema;
        }
        return '';
      });

      generator.generate();

      // Verify enum was used in generated DTO
      const dtoFileCalls = mockFs.writeFileSync.mock.calls.filter((call) =>
        call[0].toString().includes('enummodel-response.dto.ts'),
      );
      expect(dtoFileCalls.length).toBe(1);

      const dtoContent = dtoFileCalls[0]?.[1] as string;
      expect(dtoContent).toContain('Status');
      // Check that enum import or type reference exists
      expect(dtoContent).toMatch(/Status|status/);
    });

    it('should handle availableModels set correctly', () => {
      generator.generate();

      // Verify DTOs were generated for both models
      const dtoFileCalls = mockFs.writeFileSync.mock.calls.filter((call) =>
        call[0].toString().includes('-response.dto.ts'),
      );
      expect(dtoFileCalls.length).toBe(2);

      // Both DTOs should contain proper class names
      const userDtoContent = dtoFileCalls.find((call) =>
        call[0].toString().includes('user-response.dto.ts'),
      )?.[1] as string;
      const postDtoContent = dtoFileCalls.find((call) =>
        call[0].toString().includes('post-response.dto.ts'),
      )?.[1] as string;

      expect(userDtoContent).toContain('UserResponseDto');
      expect(postDtoContent).toContain('PostResponseDto');
    });
  });

  describe('Console Output Verification', () => {
    it('should output all expected log messages in sequence', () => {
      generator.generate();

      const logCalls = (console.log as jest.Mock).mock.calls.map((call) => call[0]);

      expect(logCalls).toContain('🚀 Starting DTO generation...');
      expect(logCalls).toContain('📁 Setting up output directory...');
      expect(logCalls).toContain('📖 Parsing Prisma schema...');
      expect(logCalls).toContain('📋 Found model: User');
      expect(logCalls).toContain('📋 Found model: Post');
      expect(logCalls).toContain('📊 Found 2 models in schema');
      expect(logCalls).toContain('📝 Generating DTO files...');
      expect(logCalls).toContain('✅ Generated user-response.dto.ts');
      expect(logCalls).toContain('✅ Generated post-response.dto.ts');
      expect(logCalls).toContain('📄 Generating index file...');
      expect(logCalls).toContain('✅ Generated index.ts');
      expect(logCalls).toContain('🎨 Formatting generated files...');
      expect(logCalls).toContain('✅ DTO generation completed successfully!');
    });

    it('should not output error messages on success', () => {
      generator.generate();

      expect(console.error).not.toHaveBeenCalled();
    });

    it('should output error message on failure', () => {
      const error = new Error('Test error');
      mockFs.readFileSync.mockImplementation(() => {
        throw error;
      });

      try {
        generator.generate();
      } catch {
        // Expected to throw
      }

      expect(console.error).toHaveBeenCalledWith('❌ Error during DTO generation:', error);
    });
  });

  describe('Snapshot Tests', () => {
    it('should snapshot complete DTO generation workflow output', () => {
      // Override schema content for this specific test
      const testSchema = `
// @tg_form()
model User {
  id String @id
}
`;
      mockFs.readFileSync.mockImplementation((filePath: string) => {
        if (filePath.toString().includes('schema.prisma')) {
          return testSchema;
        }
        return '';
      });

      generator.generate();

      // Snapshot the writeFileSync calls (using real NestDtoGenerator)
      const writeFileCalls = mockFs.writeFileSync.mock.calls.map((call, index) => ({
        filePath: call[0],
        content: call[1],
        callIndex: index,
      }));

      expect(writeFileCalls).toMatchSnapshot();
    });

    it('should snapshot generated index file structure', () => {
      // Override schema content for this specific test
      const testSchema = `
// @tg_form()
model User {
  id String @id
}
`;
      mockFs.readFileSync.mockImplementation((filePath: string) => {
        if (filePath.toString().includes('schema.prisma')) {
          return testSchema;
        }
        return '';
      });

      generator.generate();

      // Find and snapshot the index file
      const indexCall = mockFs.writeFileSync.mock.calls.find((call) => call[0].toString().includes('index.ts'));

      expect(indexCall?.[1]).toMatchSnapshot();
    });

    it('should snapshot complete generation process with all field types', () => {
      // Override schema content for this specific test
      const testSchema = `
// @tg_form()
model User {
  id String @id
}
`;
      mockFs.readFileSync.mockImplementation((filePath: string) => {
        if (filePath.toString().includes('schema.prisma')) {
          return testSchema;
        }
        return '';
      });

      generator.generate();

      // Snapshot the actual generated DTO content (using real NestDtoGenerator)
      const dtoFileCalls = mockFs.writeFileSync.mock.calls.filter((call) =>
        call[0].toString().includes('-response.dto.ts'),
      );
      expect(dtoFileCalls.length).toBe(1);

      const dtoContent = dtoFileCalls[0]?.[1] as string;
      expect(dtoContent).toMatchSnapshot();
    });

    it('should snapshot file generation with mixed case model names', () => {
      // Override schema content for this specific test
      const testSchema = `
// @tg_form()
model User {
  id String @id
}
`;
      mockFs.readFileSync.mockImplementation((filePath: string) => {
        if (filePath.toString().includes('schema.prisma')) {
          return testSchema;
        }
        return '';
      });

      generator.generate();

      // Snapshot the file paths generated
      const filePaths = mockFs.writeFileSync.mock.calls
        .map((call) => call[0])
        .filter((path) => !path.toString().includes('index.ts'));

      expect(filePaths).toMatchSnapshot();

      // Snapshot the index exports
      const indexCall = mockFs.writeFileSync.mock.calls.find((call) => call[0].toString().includes('index.ts'));
      expect(indexCall?.[1]).toMatchSnapshot();
    });

    it('should snapshot complete generation workflow output', () => {
      // Override schema content for this specific test
      const testSchema = `
// @tg_form()
model User {
  id String @id
}
`;
      mockFs.readFileSync.mockImplementation((filePath: string) => {
        if (filePath.toString().includes('schema.prisma')) {
          return testSchema;
        }
        return '';
      });

      generator.generate();

      // Snapshot the complete execution flow
      const dtoFileCalls = mockFs.writeFileSync.mock.calls.filter((call) =>
        call[0].toString().includes('-response.dto.ts'),
      );
      const executionSnapshot = {
        parseSchemaCalls: 1, // Schema parsing happens once via real parser
        dtoFilesGenerated: dtoFileCalls.length, // Using real NestDtoGenerator
        writeFileSyncCalls: mockFs.writeFileSync.mock.calls.length,
        formatGeneratedFileCalls: mockFormatGeneratedFile.mock.calls.length,
        tagAutoGeneratedCalls: mockTagAutoGenerated.mock.calls.length,
        filePaths: mockFs.writeFileSync.mock.calls.map((call) => call[0]),
        consoleLogs: (console.log as jest.Mock).mock.calls.map((call) => call[0]),
      };

      expect(executionSnapshot).toMatchSnapshot();
    });
  });
});
