import * as fs from 'fs';
import * as path from 'path';
import type { PrismaModel, Config } from '@tg-scripts/types';
import { tagAutoGenerated } from './src/generator/utils';
import { formatGeneratedFile } from './src/io/utils';
import { PrismaFieldParser } from './src/parser/prisma-field-parser/PrismaFieldParser';
import { PrismaSchemaParser } from './src/parser/prisma-schema-parser/PrismaSchemaParser';
import { NestDtoGenerator } from './src/generator/nest-dto-generator/NestDtoGenerator';
import { PrismaRelationsParser } from './src/parser/prisma-relation-parser/PrismaRelationsParser';
import { config } from './config';

export class DtoGenerator {
  private schemaPath: string;
  private outputDir: string;
  private models: PrismaModel[] = [];
  private enums: Map<string, string[]> = new Map();

  private config: Config;
  private fieldParser: PrismaFieldParser;
  private fieldRelationsParser: PrismaRelationsParser;
  private schemaParser: PrismaSchemaParser;
  private dtoGenerator: NestDtoGenerator;

  constructor(config: Config) {
    this.schemaPath = config.schemaPath;
    this.outputDir = config.dtosPath;
    this.config = config;
    this.fieldParser = new PrismaFieldParser();
    this.fieldRelationsParser = new PrismaRelationsParser();
    this.schemaParser = new PrismaSchemaParser(this.fieldParser, this.fieldRelationsParser);
    this.dtoGenerator = new NestDtoGenerator({ suffix: config.suffix });
  }

  generate(): void {
    console.log('🚀 Starting DTO generation...');

    try {
      this.setupOutputDirectory();
      this.parseSchema();
      this.generateDtos();
      this.generateIndexFile();
      this.formatFiles();
      console.log('✅ DTO generation completed successfully!');
    } catch (error) {
      console.error('❌ Error during DTO generation:', error);
      process.exit(1);
    }
  }

  private setupOutputDirectory(): void {
    console.log('📁 Setting up output directory...');
    if (fs.existsSync(this.outputDir)) {
      fs.rmSync(this.outputDir, { recursive: true, force: true });
    }
    fs.mkdirSync(this.outputDir, { recursive: true });
  }

  private parseSchema(): void {
    console.log('📖 Parsing Prisma schema...');
    const schemaContent = fs.readFileSync(this.schemaPath, 'utf-8');
    this.schemaParser.load(schemaContent);
    const parsed = this.schemaParser.parse();

    this.models = parsed.models;
    this.enums = parsed.enums;

    this.models.forEach((model) => {
      console.log(`📋 Found model: ${model.name}`);
    });

    console.log(`📊 Found ${this.models.length} models in schema`);
  }

  private generateDtos(): void {
    console.log('📝 Generating DTO files...');

    for (const model of this.models) {
      const content = this.dtoGenerator.generate({
        model,
        dtoType: 'response',
        enums: this.enums,
      });
      const taggedContent = tagAutoGenerated(content, model.name, 'DTO Generator');
      const fileName = `${model.name.toLowerCase()}-response.dto.ts`;
      const filePath = path.join(this.outputDir, fileName);

      fs.writeFileSync(filePath, taggedContent);
      formatGeneratedFile(filePath, process.cwd());
      console.log(`✅ Generated ${fileName}`);
    }
  }

  private generateIndexFile(): void {
    console.log('📄 Generating index file...');
    const indexContent = this.models
      .map((model) => `export * from './${model.name.toLowerCase()}-response.dto';`)
      .join('\n');

    const taggedIndexContent = tagAutoGenerated(indexContent, undefined, 'DTO Generator');

    fs.writeFileSync(path.join(this.outputDir, 'index.ts'), taggedIndexContent);
    formatGeneratedFile(path.join(this.outputDir, 'index.ts'), process.cwd());
    console.log('✅ Generated index.ts');
  }

  private formatFiles(): void {
    console.log('🎨 Formatting generated files...');
    // Files are already formatted individually, but we format index.ts again for consistency
  }
}

// Run the generator (skip in test environments)
// istanbul ignore next - CLI execution block, not testable in unit tests
if (!process.env.JEST_WORKER_ID && !process.env.NODE_ENV?.includes('test')) {
  const generator = new DtoGenerator(config);
  generator.generate();
}
