import * as fs from 'fs';
import { ApiGenerator } from './generate-api';
import { tagAutoGenerated } from './src/generator/utils/auto-text';
import { toCamelCase, toKebabCase, pluralize, getResourceName } from './src/generator/utils/naming';
import {
  formatGeneratedFile as formatGeneratedFileUtil,
  formatGeneratedFiles as formatGeneratedFilesUtil,
  promptUser,
} from './src/io/utils';
import type { PrismaModel, Config } from '@tg-scripts/types';

const config: Config = {
  schemaPath: 'prisma/schema.prisma',
  dashboardPath: 'src/dashboard/src',
  dtosPath: 'src/dtos/generated',
  suffix: 'Tg',
  updateDataProvider: true,
};

const mockFindModulePath = jest.fn();
const mockGetModuleFileName = jest.fn();
const mockUpdateImportStatements = jest.fn();
const mockUpdateImportsArray = jest.fn();
const mockGenerateTgImportStatements = jest.fn();
const mockAddImportsToModule = jest.fn();
const mockAddToArrayInModule = jest.fn();
const mockExtractCustomEndpoints = jest.fn();
const mockGenerateEndpointMappings = jest.fn();
const mockBuildEndpointMap = jest.fn();

// Mock all dependencies
jest.mock('fs', () => {
  const actualFs = jest.requireActual('fs');
  return {
    ...actualFs,
    existsSync: jest.fn(),
    readFileSync: jest.fn(),
    writeFileSync: jest.fn(),
    mkdirSync: jest.fn(),
    promises: {
      writeFile: jest.fn().mockResolvedValue(undefined),
    },
  };
});

jest.mock('./src/io/utils');
jest.mock('./src/generator/utils/auto-text');
jest.mock('./src/generator/utils/naming');
jest.mock('./src/io/module-path-resolver/ModulePathResolver', () => ({
  ModulePathResolver: jest.fn().mockImplementation(() => ({
    findModulePath: mockFindModulePath,
    getModuleFileName: mockGetModuleFileName,
  })),
}));
jest.mock('./src/generator/nest-app-module-updater/NestAppModuleUpdater', () => ({
  NestAppModuleUpdater: jest.fn().mockImplementation(() => ({
    updateImportStatements: mockUpdateImportStatements,
    updateImportsArray: mockUpdateImportsArray,
  })),
}));
jest.mock('./src/generator/nest-module-updater/NestModuleUpdater', () => ({
  NestModuleUpdater: jest.fn().mockImplementation(() => ({
    generateModuleImportStatements: mockGenerateTgImportStatements,
    addImportsToModule: mockAddImportsToModule,
    addToArrayInModule: mockAddToArrayInModule,
  })),
}));
jest.mock('./src/generator/data-provider-endpoint-generator/DataProviderEndpointGenerator', () => ({
  DataProviderEndpointGenerator: jest.fn().mockImplementation(() => ({
    extractCustomEndpoints: mockExtractCustomEndpoints,
    generateEndpointMappings: mockGenerateEndpointMappings,
    buildEndpointMap: mockBuildEndpointMap,
  })),
}));

// Mock console methods
const originalConsole = global.console;
beforeAll(() => {
  global.console = {
    ...originalConsole,
    log: jest.fn(),
    error: jest.fn(),
    warn: jest.fn(),
  };
});

afterAll(() => {
  global.console = originalConsole;
});

// Prevent the script from running when imported
const originalEnv = process.env;
beforeEach(() => {
  process.env.JEST_WORKER_ID = 'test';
});

afterEach(() => {
  process.env = originalEnv;
});

describe('TgApiGenerator', () => {
  let generator: ApiGenerator;
  let mockFs: jest.Mocked<typeof fs>;
  let mockFsPromisesWriteFile: jest.MockedFunction<typeof fs.promises.writeFile>;
  let mockPromptUser: jest.MockedFunction<typeof promptUser>;
  let mockTagAutoGenerated: jest.MockedFunction<typeof tagAutoGenerated>;
  let mockToCamelCase: jest.MockedFunction<typeof toCamelCase>;
  let mockToKebabCase: jest.MockedFunction<typeof toKebabCase>;
  let mockPluralize: jest.MockedFunction<typeof pluralize>;
  let mockGetResourceName: jest.MockedFunction<typeof getResourceName>;
  let mockFormatGeneratedFile: jest.MockedFunction<typeof formatGeneratedFileUtil>;
  let mockFormatGeneratedFiles: jest.MockedFunction<typeof formatGeneratedFilesUtil>;
  let mockProcessCwd: jest.SpyInstance;
  let mockProcessExit: jest.SpyInstance;

  const mockModels: PrismaModel[] = [
    {
      name: 'User',
      fields: [
        {
          name: 'id',
          baseType: 'String',
          type: 'String',
          isOptional: false,
          isArray: false,
          isId: true,
          isUnique: false,
          hasDefaultValue: false,
          customValidations: [],
        },
        {
          name: 'email',
          baseType: 'String',
          type: 'String',
          isOptional: false,
          isArray: false,
          isId: false,
          isUnique: true,
          hasDefaultValue: false,
          customValidations: [],
        },
      ],
      enums: [],
      moduleType: 'features',
    },
    {
      name: 'Post',
      fields: [
        {
          name: 'id',
          baseType: 'String',
          type: 'String',
          isOptional: false,
          isArray: false,
          isId: true,
          isUnique: false,
          hasDefaultValue: false,
          customValidations: [],
        },
        {
          name: 'title',
          baseType: 'String',
          type: 'String',
          isOptional: false,
          isArray: false,
          isId: false,
          isUnique: false,
          hasDefaultValue: false,
          customValidations: [],
        },
      ],
      enums: [],
      moduleType: 'features',
    },
  ];

  beforeEach(() => {
    jest.clearAllMocks();
    mockFindModulePath.mockReset();
    mockGetModuleFileName.mockReset();
    mockUpdateImportStatements.mockReset();
    mockUpdateImportsArray.mockReset();
    mockGenerateTgImportStatements.mockReset();
    mockAddImportsToModule.mockReset();
    mockAddToArrayInModule.mockReset();
    mockExtractCustomEndpoints.mockReset();
    mockGenerateEndpointMappings.mockReset();
    mockBuildEndpointMap.mockReset();

    // Setup mocks
    mockFs = fs as jest.Mocked<typeof fs>;
    mockFsPromisesWriteFile = fs.promises.writeFile as jest.MockedFunction<typeof fs.promises.writeFile>;
    mockPromptUser = promptUser as jest.MockedFunction<typeof promptUser>;
    mockTagAutoGenerated = tagAutoGenerated as jest.MockedFunction<typeof tagAutoGenerated>;
    mockToCamelCase = jest.mocked(toCamelCase);
    mockToKebabCase = jest.mocked(toKebabCase);
    mockPluralize = jest.mocked(pluralize);
    mockGetResourceName = jest.mocked(getResourceName);
    mockFormatGeneratedFile = formatGeneratedFileUtil as jest.MockedFunction<typeof formatGeneratedFileUtil>;
    mockFormatGeneratedFiles = formatGeneratedFilesUtil as jest.MockedFunction<typeof formatGeneratedFilesUtil>;

    // Mock process.cwd()
    mockProcessCwd = jest.spyOn(process, 'cwd').mockReturnValue('/mock/project/root');

    // Mock process.exit()
    mockProcessExit = jest.spyOn(process, 'exit').mockImplementation((code?: number) => {
      throw new Error(`Process exit called with code: ${code}`);
    });

    // Default implementations
    mockFs.existsSync.mockReturnValue(true);
    // Provide real schema content that the parser can parse
    const defaultSchema = `
// @tg_form()
model User {
  id String @id @default(uuid())
  firstName String
  lastName String
  email String @unique
}

// @tg_form()
model Post {
  id String @id @default(uuid())
  title String
  content String?
}
`;
    mockFs.readFileSync.mockImplementation((filePath: string) => {
      if (filePath.toString().includes('schema.prisma')) {
        return defaultSchema;
      }
      if (filePath.toString().includes('app.module.ts')) {
        return 'app module content';
      }
      if (filePath.toString().includes('dataProvider.ts')) {
        return 'const endpointMap: Record<string, string> = {\n};';
      }
      return '';
    });
    mockFs.writeFileSync.mockImplementation(() => {});
    mockFs.mkdirSync.mockReturnValue(undefined);

    mockTagAutoGenerated.mockImplementation((text) => text);
    mockToCamelCase.mockImplementation((name) => name.charAt(0).toLowerCase() + name.slice(1));
    mockToKebabCase.mockImplementation((name) => {
      return name
        .replace(/([a-z])([A-Z])/g, '$1-$2')
        .replace(/([A-Z])([A-Z][a-z])/g, '$1-$2')
        .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
        .toLowerCase();
    });
    mockPluralize.mockImplementation((name) => {
      return name.endsWith('s') ? name : `${name}s`;
    });
    mockGetResourceName.mockImplementation((name) => {
      const kebab = mockToKebabCase(name);
      return mockPluralize(kebab);
    });
    // Default: module found
    mockFindModulePath.mockReturnValue({
      path: '/mock/project/root/src/features/user',
      type: 'features',
      folderName: 'user',
    });
    mockGetModuleFileName.mockReturnValue('user.module.ts');
    mockFormatGeneratedFile.mockImplementation(() => {});
    mockFormatGeneratedFiles.mockImplementation(() => {});
    mockUpdateImportStatements.mockImplementation((content) => content);
    mockUpdateImportsArray.mockImplementation((content) => content);
    mockGenerateTgImportStatements.mockReturnValue({
      controllerImport: 'import { UserTgController } from "./user.tg.controller";',
      serviceImport: 'import { UserTgService } from "./user.tg.service";',
    });
    mockAddImportsToModule.mockImplementation((content) => content);
    mockAddToArrayInModule.mockImplementation((content) => content);
    mockExtractCustomEndpoints.mockReturnValue('');
    mockGenerateEndpointMappings.mockReturnValue('');
    mockBuildEndpointMap.mockReturnValue('const endpointMap: Record<string, string> = {};');

    generator = new ApiGenerator(config);
  });

  afterEach(() => {
    mockProcessCwd.mockRestore();
    mockProcessExit.mockRestore();
  });

  describe('generate', () => {
    it('should complete full generation process successfully', async () => {
      await generator.generate();

      expect(mockFs.readFileSync).toHaveBeenCalled();
      expect(console.log).toHaveBeenCalledWith('✅ API generation completed successfully!');
    });

    it('should exit with code 1 on error', async () => {
      const error = new Error('Test error');
      mockFs.readFileSync.mockImplementation(() => {
        throw error;
      });

      await expect(generator.generate()).rejects.toThrow('Process exit called with code: 1');
      expect(console.error).toHaveBeenCalledWith('❌ Error during API generation:', error);
      expect(mockProcessExit).toHaveBeenCalledWith(1);
    });
  });

  describe('parseSchema', () => {
    it('should parse schema content', async () => {
      await generator.generate();

      expect(mockFs.readFileSync).toHaveBeenCalled();
      expect(generator['models'].length).toBeGreaterThan(0);
    });

    it('should log each found model', async () => {
      await generator.generate();

      expect(console.log).toHaveBeenCalledWith('📋 Found model with @tg_form(): User');
      expect(console.log).toHaveBeenCalledWith('📋 Found model with @tg_form(): Post');
    });

    it('should log total model count', async () => {
      await generator.generate();

      expect(console.log).toHaveBeenCalledWith('📊 Found 2 models with @tg_form()');
    });
  });

  describe('findModules', () => {
    it('should use existing module path when found', async () => {
      await generator.generate();

      expect(mockFindModulePath).toHaveBeenCalledWith('User', '/mock/project/root');
      expect(console.log).toHaveBeenCalledWith(expect.stringContaining('✅ Found module for User'));
    });

    it('should prompt user when module not found', async () => {
      // Reset and override the default mock to return null for all calls
      mockFindModulePath.mockReset();
      mockFindModulePath.mockImplementation(() => null);
      mockPromptUser.mockResolvedValue(false);

      await generator.generate();

      // Verify findModulePath was called
      expect(mockFindModulePath).toHaveBeenCalled();

      expect(mockPromptUser).toHaveBeenCalled();
      expect(console.log).toHaveBeenCalledWith(expect.stringContaining('⚠️ No module found for User'));
      expect(console.log).toHaveBeenCalledWith(expect.stringContaining('⏭️ Skipping User'));
    });

    it('should create module when user confirms', async () => {
      // Reset and override the default mock to return null for all calls
      mockFindModulePath.mockReset();
      mockFindModulePath.mockImplementation(() => null);
      mockPromptUser.mockResolvedValue(true);

      await generator.generate();

      // Verify findModulePath was called
      expect(mockFindModulePath).toHaveBeenCalled();

      expect(mockFs.mkdirSync).toHaveBeenCalled();
      expect(mockFs.writeFileSync).toHaveBeenCalled();
      expect(console.log).toHaveBeenCalledWith(expect.stringContaining('📁 Created module directory'));
    });

    it('should track auto-created modules', async () => {
      // Reset and override the default mock to return null for all calls
      mockFindModulePath.mockReset();
      mockFindModulePath.mockImplementation(() => null);
      mockPromptUser.mockResolvedValue(true);

      await generator.generate();

      // Verify findModulePath was called
      expect(mockFindModulePath).toHaveBeenCalled();

      expect(mockUpdateImportStatements).toHaveBeenCalled();
      expect(mockUpdateImportsArray).toHaveBeenCalled();
    });

    it('should skip updateAppModule when no auto-created modules', async () => {
      mockFindModulePath.mockReturnValue({
        path: '/mock/project/root/src/features/user',
        type: 'features',
        folderName: 'user',
      });

      await generator.generate();

      // Should not call updateImportStatements or updateImportsArray with modules
      expect(mockFs.writeFileSync).toHaveBeenCalled();
    });
  });

  describe('generateTgFiles', () => {
    it('should generate DTOs for each model', async () => {
      await generator.generate();

      const writeCalls = mockFsPromisesWriteFile.mock.calls;
      const createDtoCall = writeCalls.find((call) => {
        const filePath = call[0] as string;
        return filePath.includes('create-') && filePath.includes('.tg.dto.ts');
      });
      const updateDtoCall = writeCalls.find((call) => {
        const filePath = call[0] as string;
        return filePath.includes('update-') && filePath.includes('.tg.dto.ts');
      });

      expect(createDtoCall).toBeDefined();
      expect(updateDtoCall).toBeDefined();

      const createDtoContent = createDtoCall?.[1] as string;
      const updateDtoContent = updateDtoCall?.[1] as string;

      expect(createDtoContent).toContain('export class Create');
      expect(createDtoContent).toContain('TgDto');
      expect(updateDtoContent).toContain('export class Update');
      expect(updateDtoContent).toContain('TgDto');
      expect(createDtoContent).toContain('@ApiProperty');
      expect(updateDtoContent).toContain('@ApiProperty');
    });

    it('should generate service for each model', async () => {
      await generator.generate();

      const writeCalls = mockFsPromisesWriteFile.mock.calls;
      const serviceCall = writeCalls.find((call) => {
        const filePath = call[0] as string;
        return filePath.includes('.tg.service.ts');
      });
      expect(serviceCall).toBeDefined();
      const serviceContent = serviceCall?.[1] as string;
      expect(serviceContent).toContain('@Injectable()');
      expect(serviceContent).toContain('TgService');
    });

    it('should generate controller for each model', async () => {
      await generator.generate();

      const writeCalls = mockFsPromisesWriteFile.mock.calls;
      const controllerCall = writeCalls.find((call) => {
        const filePath = call[0] as string;
        return filePath.includes('.tg.controller.ts');
      });
      expect(controllerCall).toBeDefined();
      const controllerContent = controllerCall?.[1] as string;
      expect(controllerContent).toContain('@Controller');
      expect(controllerContent).toContain('TgController');
      expect(controllerContent).toContain('@ApiTags');
    });

    it('should skip models without module path', async () => {
      // Reset models to ensure no modulePath
      // Use a schema that will produce models without module paths
      const schemaWithoutPaths = `
// @tg_form()
model User {
  id String @id
}
`;
      mockFs.readFileSync.mockImplementation((filePath: string) => {
        if (filePath.toString().includes('schema.prisma')) {
          return schemaWithoutPaths;
        }
        if (filePath.toString().includes('app.module.ts')) {
          return 'app module content';
        }
        if (filePath.toString().includes('dataProvider.ts')) {
          return 'const endpointMap: Record<string, string> = {\n};';
        }
        return '';
      });
      mockFindModulePath.mockReturnValue(null);
      mockPromptUser.mockResolvedValue(false);

      await generator.generate();

      expect(console.log).toHaveBeenCalledWith(expect.stringContaining('⏭️ Skipping'));
      // Verify no DTO files were written
      const dtoCalls = mockFsPromisesWriteFile.mock.calls.filter((call) => {
        const filePath = call[0] as string;
        return filePath.includes('.tg.dto.ts');
      });
      expect(dtoCalls.length).toBe(0);
    });

    it('should update module for each model', async () => {
      await generator.generate();

      expect(mockGetModuleFileName).toHaveBeenCalled();
      expect(mockGenerateTgImportStatements).toHaveBeenCalled();
    });
  });

  describe('createModuleFile', () => {
    it('should create module file with correct content', async () => {
      mockFindModulePath.mockReturnValue(null);
      mockPromptUser.mockResolvedValue(true);

      await generator.generate();

      expect(mockFs.writeFileSync).toHaveBeenCalled();
    });
  });

  describe('updateAppModule', () => {
    it('should update import statements', async () => {
      // Reset and override the default mock to return null for all calls
      mockFindModulePath.mockReset();
      mockFindModulePath.mockImplementation(() => null);
      mockPromptUser.mockResolvedValue(true);

      await generator.generate();

      expect(mockUpdateImportStatements).toHaveBeenCalled();
      expect(mockUpdateImportsArray).toHaveBeenCalled();
      expect(mockFs.writeFileSync).toHaveBeenCalled();
      expect(mockFormatGeneratedFile).toHaveBeenCalled();
    });

    it('should skip when no modules provided', () => {
      mockFindModulePath.mockReturnValue({
        path: '/mock/project/root/src/features/user',
        type: 'features',
        folderName: 'user',
      });

      const appModuleWriteCalls = mockFs.writeFileSync.mock.calls.filter((call) =>
        String(call[0]).includes('app.module.ts'),
      );

      expect(appModuleWriteCalls.length).toBe(0);
    });
  });

  describe('generateCreateDto', () => {
    it('should generate create DTO file', async () => {
      await generator.generate();

      const writeCalls = mockFsPromisesWriteFile.mock.calls;
      const createDtoCall = writeCalls.find((call) => {
        const filePath = call[0] as string;
        return filePath.includes('create-') && filePath.includes('.tg.dto.ts');
      });

      expect(createDtoCall).toBeDefined();
      const createDtoContent = createDtoCall?.[1] as string;
      expect(createDtoContent).toContain('Create');
      expect(createDtoContent).toContain('TgDto');
      expect(mockTagAutoGenerated).toHaveBeenCalled();
      expect(mockFormatGeneratedFiles).toHaveBeenCalled();
    });
  });

  describe('generateUpdateDto', () => {
    it('should generate update DTO file', async () => {
      await generator.generate();

      const writeCalls = mockFsPromisesWriteFile.mock.calls;
      const updateDtoCall = writeCalls.find((call) => {
        const filePath = call[0] as string;
        return filePath.includes('update-') && filePath.includes('.tg.dto.ts');
      });

      expect(updateDtoCall).toBeDefined();
      const updateDtoContent = updateDtoCall?.[1] as string;
      expect(updateDtoContent).toContain('Update');
      expect(updateDtoContent).toContain('TgDto');
      expect(mockTagAutoGenerated).toHaveBeenCalled();
      expect(mockFormatGeneratedFiles).toHaveBeenCalled();
    });
  });

  describe('generateService', () => {
    it('should generate service with correct methods', async () => {
      await generator.generate();

      const writeCalls = mockFsPromisesWriteFile.mock.calls;
      const serviceCall = writeCalls.find((call) => {
        const filePath = call[0] as string;
        return filePath.includes('.tg.service.ts');
      });
      expect(serviceCall).toBeDefined();
      const serviceContent = serviceCall?.[1] as string;

      // Check that the service contains all expected methods
      expect(serviceContent).toContain('getList');
      expect(serviceContent).toContain('getOne');
      expect(serviceContent).toContain('getMany');
      expect(serviceContent).toContain('getManyReference');
      expect(serviceContent).toContain('create');
      expect(serviceContent).toContain('update');
      expect(serviceContent).toContain('updateMany');
      expect(serviceContent).toContain('deleteOne');
      expect(serviceContent).toContain('deleteMany');
      expect(serviceContent).toContain('getSelectFields');
    });

    it('should filter password fields from searchable and select fields', async () => {
      // Override schema to have model with password field
      const schemaWithPassword = `
// @tg_form()
model User {
  id String @id
  password String
  email String
}
`;
      mockFs.readFileSync.mockImplementation((filePath: string) => {
        if (filePath.toString().includes('schema.prisma')) {
          return schemaWithPassword;
        }
        if (filePath.toString().includes('app.module.ts')) {
          return 'app module content';
        }
        if (filePath.toString().includes('dataProvider.ts')) {
          return 'const endpointMap: Record<string, string> = {\n};';
        }
        return '';
      });

      await generator.generate();

      const writeCalls = mockFsPromisesWriteFile.mock.calls;
      const serviceCall = writeCalls.find((call) => {
        const filePath = call[0] as string;
        return filePath.includes('.tg.service.ts');
      });
      const serviceContent = serviceCall?.[1] as string;

      expect(serviceContent).not.toContain('password');
      expect(serviceContent).toContain('email');
    });
  });

  describe('generateController', () => {
    it('should generate controller with correct methods', async () => {
      await generator.generate();

      const writeCalls = mockFsPromisesWriteFile.mock.calls;
      const controllerCall = writeCalls.find((call) => {
        const filePath = call[0] as string;
        return filePath.includes('.tg.controller.ts');
      });
      expect(controllerCall).toBeDefined();
      const controllerContent = controllerCall?.[1] as string;

      // Check that the controller contains all expected methods
      expect(controllerContent).toContain('getList');
      expect(controllerContent).toContain('getOne');
      expect(controllerContent).toContain('getMany');
      expect(controllerContent).toContain('getManyReference');
      expect(controllerContent).toContain('create');
      expect(controllerContent).toContain('update');
      expect(controllerContent).toContain('updateMany');
      expect(controllerContent).toContain('deleteOne');
      expect(controllerContent).toContain('deleteMany');
    });
  });

  describe('updateModule', () => {
    it('should update existing module file', async () => {
      mockGetModuleFileName.mockReturnValue('user.module.ts');

      await generator.generate();

      expect(mockGenerateTgImportStatements).toHaveBeenCalled();
      expect(mockAddImportsToModule).toHaveBeenCalled();
      expect(mockAddToArrayInModule).toHaveBeenCalled();
    });

    it('should create module file if not found', async () => {
      mockGetModuleFileName.mockReturnValue('');

      await generator.generate();

      expect(mockFs.writeFileSync).toHaveBeenCalled();
      expect(console.log).toHaveBeenCalledWith(expect.stringContaining('📄 Creating module file'));
    });

    it('should skip when no module path', async () => {
      // Reset models to ensure no modulePath
      // Use a schema that will produce models without module paths
      const schemaWithoutPaths = `
// @tg_form()
model User {
  id String @id
}
`;
      mockFs.readFileSync.mockImplementation((filePath: string) => {
        if (filePath.toString().includes('schema.prisma')) {
          return schemaWithoutPaths;
        }
        if (filePath.toString().includes('app.module.ts')) {
          return 'app module content';
        }
        if (filePath.toString().includes('dataProvider.ts')) {
          return 'const endpointMap: Record<string, string> = {\n};';
        }
        return '';
      });
      mockFindModulePath.mockReturnValue(null);
      mockPromptUser.mockResolvedValue(false);

      await generator.generate();

      expect(mockGetModuleFileName).not.toHaveBeenCalled();
      expect(console.log).toHaveBeenCalledWith(expect.stringContaining('⏭️ Skipping'));
      expect(console.log).toHaveBeenCalledWith(expect.stringContaining('no module path'));
    });

    it('should handle missing modulePath in updateModule defensive check', () => {
      // Directly test the defensive check in updateModule by calling it
      // with a model that has no modulePath (even though this shouldn't happen in normal flow)
      const modelWithoutPath: PrismaModel = {
        ...mockModels[0],
        modulePath: undefined,
      };

      // Access private method via type assertion
      (generator as any).updateModule(modelWithoutPath);

      expect(console.log).toHaveBeenCalledWith(`⚠️ No module path for ${modelWithoutPath.name}`);
    });
  });

  describe('updateDataProvider', () => {
    it('should update dataProvider endpoint map', async () => {
      jest.clearAllMocks(); // Clear previous mocks for this test
      const dataProviderContent = `const endpointMap: Record<string, string> = {
  'user': '/api/tg/users',
};`;

      mockFs.readFileSync.mockImplementation((filePath: string) => {
        if (filePath.toString().includes('schema.prisma')) {
          return 'schema content';
        }
        if (filePath.toString().includes('dataProvider.ts')) {
          return dataProviderContent;
        }
        return '';
      });

      await generator.generate();

      expect(mockExtractCustomEndpoints).toHaveBeenCalledWith(expect.any(String));
      expect(mockGenerateEndpointMappings).toHaveBeenCalledWith(
        expect.any(Array),
        expect.any(Function),
        expect.any(Function),
      );
      expect(mockBuildEndpointMap).toHaveBeenCalledWith(expect.any(String), expect.any(String));
      expect(mockFs.writeFileSync).toHaveBeenCalled();
    });

    it('should skip when endpointMap not found', async () => {
      mockFs.readFileSync.mockImplementation((filePath: string) => {
        if (filePath.toString().includes('schema.prisma')) {
          return 'schema content';
        }
        if (filePath.toString().includes('dataProvider.ts')) {
          return 'no endpoint map here';
        }
        return '';
      });

      await generator.generate();

      expect(console.log).toHaveBeenCalledWith(expect.stringContaining('⚠️ Could not find endpointMap'));
    });
  });
});
