import * as fs from 'fs';
import * as path from 'path';
import type { Config, Guard, PrismaModel } from '@tg-scripts/types';
import { getResourceName, pluralize, toCamelCase, toKebabCase } from '../utils/naming';
import { tagAutoGenerated } from '../utils/auto-text';
import { formatGeneratedFile, formatGeneratedFiles, promptUser } from '../../io/utils';
import { ModulePathResolver } from '../../io/module-path-resolver/ModulePathResolver';
import { ProjectPathResolver } from '../../io/project-paths/ProjectPathResolver';
import { NestAppModuleUpdater } from '../nest-app-module-updater/NestAppModuleUpdater';
import { NestModuleUpdater } from '../nest-module-updater/NestModuleUpdater';
import { DataProviderEndpointGenerator } from '../data-provider-endpoint-generator/DataProviderEndpointGenerator';
import { PrismaFieldParser } from '../../parser/prisma-field-parser/PrismaFieldParser';
import { PrismaRelationsParser } from '../../parser/prisma-relation-parser/PrismaRelationsParser';
import { PrismaSchemaParser } from '../../parser/prisma-schema-parser/PrismaSchemaParser';
import { NestDtoGenerator } from '../nest-dto-generator/NestDtoGenerator';
import { NestModuleFileGenerator } from '../nest-module-file-generator/NestModuleFileGenerator';
import { NestServiceGenerator } from '../nest-service-generator/NestServiceGenerator';
import { NestControllerGenerator } from '../nest-controller-generator/NestControllerGenerator';
import { NestStaticGenerator } from '../nest-static-generator/NestStaticGenerator';

export class ApiGenerator {
  private appModulePath: string | null;
  private appModuleUpdater: NestAppModuleUpdater;
  private autoCreatedModules: {
    name: string;
    moduleType: string;
    moduleFilePath: string;
  }[] = [];
  private config: Config;
  private controllerGenerator: NestControllerGenerator;
  private dataProviderGenerator: DataProviderEndpointGenerator;
  private dataProviderPath: string | null;
  private defaultFeatureRoot: string;
  private dtoGenerator: NestDtoGenerator;
  private enums: Map<string, string[]> = new Map();
  private fieldParser: PrismaFieldParser;
  private fieldRelationsParser: PrismaRelationsParser;
  private fileSuffix: string;
  private models: PrismaModel[] = [];
  private moduleFileGenerator: NestModuleFileGenerator;
  private modulePathResolver: ModulePathResolver;
  private moduleUpdater: NestModuleUpdater;
  private namingSuffix: string;
  private readonly nonInteractive: boolean;
  private projectPathResolver: ProjectPathResolver;
  private schemaAbsolutePath: string;
  private schemaParser: PrismaSchemaParser;
  private serviceGenerator: NestServiceGenerator;
  private workspaceRoot: string;
  constructor(config: Config) {
    this.config = config;
    this.workspaceRoot = process.cwd();
    this.schemaAbsolutePath = path.isAbsolute(config.input.prisma.schemaPath as string)
      ? (config.input.prisma.schemaPath as string)
      : path.join(this.workspaceRoot, config.input.prisma.schemaPath as string);
    this.fieldParser = new PrismaFieldParser();
    this.fieldRelationsParser = new PrismaRelationsParser();
    this.schemaParser = new PrismaSchemaParser(this.fieldParser, this.fieldRelationsParser);
    this.dtoGenerator = new NestDtoGenerator({ suffix: config.api.suffix as string });
    this.moduleFileGenerator = new NestModuleFileGenerator({ suffix: config.api.suffix });
    const baseGuards = config.api.guards ?? [];
    const adminOnlyGuards = config.api.adminGuards ?? [];
    const appliedGuards = config.api.requireAdmin
      ? [...(baseGuards as Guard[]), ...(adminOnlyGuards as Guard[])]
      : baseGuards;
    this.serviceGenerator = new NestServiceGenerator({ suffix: config.api.suffix as string });
    this.controllerGenerator = new NestControllerGenerator({
      suffix: config.api.suffix as string,
      isAdmin: config.api.requireAdmin as boolean,
      guards: appliedGuards as Guard[],
      guardsEnabled: config.api.authenticationEnabled as boolean,
      prefix: config.api.prefix as string,
      dtosPath: config.output.backend.dtosPath as string,
      workspaceRoot: this.workspaceRoot,
    });
    this.projectPathResolver = new ProjectPathResolver(config, { workspaceRoot: this.workspaceRoot });
    this.modulePathResolver = new ModulePathResolver({
      searchPaths: config.output.backend.modulesPaths as string[],
      defaultRoot: config.output.backend.root as string,
    });
    this.appModuleUpdater = new NestAppModuleUpdater();
    this.moduleUpdater = new NestModuleUpdater();
    this.dataProviderGenerator = new DataProviderEndpointGenerator();
    this.appModulePath = this.projectPathResolver.resolveAppModulePath();
    this.dataProviderPath = this.projectPathResolver.resolveDashboardDataProviderPath();
    this.defaultFeatureRoot = path.join(this.workspaceRoot, config.output.backend.root as string);
    const suffix = (config.api.suffix as string)?.trim() ?? '';
    this.namingSuffix = suffix ? `${suffix.charAt(0).toUpperCase()}${suffix.slice(1).toLowerCase()}` : '';
    this.fileSuffix = suffix.toLowerCase();
    this.nonInteractive = config.behavior.nonInteractive as boolean;
  }

  private createModuleFile(model: PrismaModel, modulePath: string): string {
    const camelCaseName = toCamelCase(model.name);

    // Compute relative path from module file to PrismaService
    const moduleFilePath = path.join(modulePath, `${camelCaseName}.module.ts`);
    const prismaServiceAbsPath = path.join(this.workspaceRoot, this.config.input.prisma.servicePath as string);
    let prismaServiceImportPath = path
      .relative(modulePath, prismaServiceAbsPath)
      .replace(/\\/g, '/')
      .replace(/\.ts$/, '');
    if (!prismaServiceImportPath.startsWith('.')) {
      prismaServiceImportPath = './' + prismaServiceImportPath;
    }

    const content = this.moduleFileGenerator.generate(model, { prismaServiceImportPath });

    fs.writeFileSync(moduleFilePath, content);
    console.log(`📄 Created module file: ${moduleFilePath}`);
    return moduleFilePath;
  }

  private async findModules(): Promise<void> {
    console.log('🔍 Finding corresponding modules...');

    for (const model of this.models) {
      const camelCaseName = toCamelCase(model.name);
      const foundModule = this.modulePathResolver.findModulePath(model.name, process.cwd());

      if (foundModule) {
        model.modulePath = foundModule.path;
        model.moduleType = foundModule.type;
        console.log(`✅ Found module for ${model.name} in ${foundModule.type}/${foundModule.folderName}`);
        continue;
      }

      // Module not found - prompt user
      console.log(`⚠️ No module found for ${model.name}`);
      console.log(
        `   Tried: ${[
          camelCaseName,
          pluralize(camelCaseName),
          toKebabCase(model.name),
          pluralize(toKebabCase(model.name)),
        ]
          .filter((v, i, a) => a.indexOf(v) === i)
          .join(', ')}`,
      );

      const shouldCreate = await promptUser(`Do you want to create the module directory for ${model.name}? (y/n): `, {
        autoConfirm: this.nonInteractive,
        defaultValue: true,
      });

      if (shouldCreate) {
        const moduleFolderName = toKebabCase(model.name);
        const modulePath = path.join(this.defaultFeatureRoot, moduleFolderName);
        fs.mkdirSync(modulePath, { recursive: true });

        // Create the module file
        const moduleFilePath = this.createModuleFile(model, modulePath);

        // Determine moduleType from the defaultRoot path
        const moduleType = path.basename(this.config.output.backend.root as string);

        model.modulePath = modulePath;
        model.moduleType = moduleType;
        this.autoCreatedModules.push({
          name: model.name,
          moduleType: moduleType,
          moduleFilePath,
        });
        console.log(`📁 Created module directory and file: ${modulePath}`);
      } else {
        console.log(`⏭️ Skipping ${model.name}...`);
      }
    }
  }

  private async generateFullNestModule(): Promise<void> {
    console.log('📝 Generating Full Nest Module files...');
    for (const model of this.models) {
      if (!model.modulePath) {
        console.log(`⏭️ Skipping ${model.name} - no module path`);
        continue;
      }

      console.log(`🔧 Generating Full Nest Module files for ${model.name}...`);
      const camelCaseName = toCamelCase(model.name);

      const createDtoContent = tagAutoGenerated(
        this.dtoGenerator.generate({ model, dtoType: 'create', enums: this.enums }),
        model.name,
      );
      const createDtoFileName = `${this.withFileSuffix(`create-${camelCaseName}`)}.dto.ts`;
      const createDtoFilePath = path.join(model.modulePath, createDtoFileName);
      const updateDtoContent = tagAutoGenerated(
        this.dtoGenerator.generate({ model, dtoType: 'update', enums: this.enums }),
        model.name,
      );
      const updateDtoFileName = `${this.withFileSuffix(`update-${camelCaseName}`)}.dto.ts`;
      const updateDtoFilePath = path.join(model.modulePath, updateDtoFileName);

      const passwordFields = model.fields
        .filter((f) => f.name === 'password' || f.tgFormat === 'password')
        .map((f) => f.name);

      const serviceFileName = `${this.withFileSuffix(camelCaseName)}.service.ts`;
      const serviceFilePath = path.join(model.modulePath, serviceFileName);

      const serviceContent = this.serviceGenerator.generate(model, {
        excludeFields: passwordFields,
        serviceFilePath: serviceFilePath,
        dtosPath: this.config.output.backend.dtosPath as string,
        utilsPath: this.config.output.backend.utilsPath as string,
        workspaceRoot: this.workspaceRoot,
        prismaServicePath: this.config.input.prisma.servicePath as string,
        models: this.models,
        relationsInclude: [],
      });

      const controllerContent = this.controllerGenerator.generate({ model });
      const controllerFileName = `${this.withFileSuffix(camelCaseName)}.controller.ts`;
      const controllerFilePath = path.join(model.modulePath, controllerFileName);

      // Collect files to write
      const filesToWrite: Array<{ path: string; content: string }> = [
        { path: createDtoFilePath, content: createDtoContent },
        { path: updateDtoFilePath, content: updateDtoContent },
        { path: serviceFilePath, content: serviceContent },
        { path: controllerFilePath, content: controllerContent },
      ];

      await Promise.all(filesToWrite.map(({ path, content }) => fs.promises.writeFile(path, content)));

      formatGeneratedFiles(
        filesToWrite.map((f) => f.path),
        process.cwd(),
      );

      // Update module
      this.updateModule(model);

      console.log(`✅ Generated Full Nest Module files for ${model.name}`);
    }
  }

  private async generateNestStaticFiles(): Promise<void> {
    console.log('🔧 Generating Nest Static files...');
    const proceed = await promptUser('Generate required static files (guards, dtos, utils)? (y/n): ', {
      autoConfirm: this.nonInteractive,
      defaultValue: true,
    });
    if (!proceed) {
      console.log('⏭️ Skipping static files generation.');
      return;
    }

    const authEnabled = this.config.api.authenticationEnabled as boolean;
    const requireAdmin = this.config.api.requireAdmin as boolean;

    const available = [
      ...(authEnabled && requireAdmin ? ['admin.guard', 'is-admin.decorator'] : []),
      'paginated-search-query.dto',
      'paginated-search-result.dto',
      'api-response.dto',
      'pagination.interceptor',
      'paginated-search.decorator',
      'paginated-search.util',
      'feature-flag.guard',
      'audit.interceptor',
    ];

    let include: string[] = [];
    if (!this.nonInteractive) {
      for (const name of available) {
        const yes = await promptUser(`Generate ${name}? (y/n): `, { defaultValue: true });
        if (yes) include.push(name);
      }
    }
    if (include.length === 0) include = available;

    const nestStaticGenerator = new NestStaticGenerator(this.config);
    await nestStaticGenerator.generate({ include });
  }

  private parseSchema(): void {
    console.log('📖 Parsing Prisma schema...');
    console.log(`   Reading from: ${this.schemaAbsolutePath}`);

    const schemaContent = fs.readFileSync(this.schemaAbsolutePath, 'utf-8');
    console.log(`   Schema content length: ${schemaContent.length} characters`);

    this.schemaParser.load(schemaContent);
    const { models, enums } = this.schemaParser.parse();

    this.models = models;
    this.enums = enums;

    if (this.models.length === 0) {
      console.warn('   ⚠️  Warning: No models with @tg_form() directive found!');
      console.warn('   ℹ️  Hint: Add @tg_form() directive to models you want to generate APIs for.');
    } else {
      models.forEach((model) => {
        console.log(`   📋 Found model with @tg_form(): ${model.name}`);
      });
    }

    console.log(`📊 Found ${this.models.length} models with @tg_form()`);
  }

  private toModuleImportPath(fromDirectory: string, moduleFilePath: string): string {
    const relativePath = path.relative(fromDirectory, moduleFilePath);
    const normalized = relativePath.split(path.sep).join('/');
    const withoutExtension = normalized.replace(/\.ts$/, '');
    if (withoutExtension.startsWith('.')) {
      return withoutExtension;
    }
    return `./${withoutExtension}`;
  }

  private updateAppModule(
    mods?: {
      name: string;
      moduleType: string;
      moduleFilePath: string;
    }[],
  ): void {
    if (!mods || mods.length === 0) return;
    console.log('🔄 Updating AppModule with auto-created modules...');

    const resolvedAppModulePath = this.appModulePath ?? this.projectPathResolver.resolveAppModulePath();
    this.appModulePath = resolvedAppModulePath;

    if (!resolvedAppModulePath) {
      console.warn('⚠️ Could not locate AppModule file. Skipping automatic AppModule updates.');
      console.warn('   Configure config.paths.appModule or ensure app.module.ts exists in a discoverable location.');
      return;
    }

    if (!fs.existsSync(resolvedAppModulePath)) {
      console.warn(`⚠️ AppModule file not found at ${resolvedAppModulePath}. Skipping update.`);
      console.warn('   Configure config.paths.appModule if your AppModule lives elsewhere.');
      return;
    }

    const appModuleDir = path.dirname(resolvedAppModulePath);
    let appModuleContent = fs.readFileSync(resolvedAppModulePath, 'utf-8');

    const registrations = mods.map((mod) => ({
      name: mod.name,
      importPath: this.toModuleImportPath(appModuleDir, mod.moduleFilePath),
    }));

    // Step 1: Parse and update import statements
    appModuleContent = this.appModuleUpdater.updateImportStatements(appModuleContent, registrations);

    // Step 2: Parse and update imports array
    appModuleContent = this.appModuleUpdater.updateImportsArray(appModuleContent, registrations);

    fs.writeFileSync(resolvedAppModulePath, appModuleContent);

    // Format the file with Prettier
    formatGeneratedFile(resolvedAppModulePath, this.workspaceRoot);

    console.log('✅ Updated AppModule with auto-created modules');
  }

  private updateDataProvider(): void {
    console.log('🔄 Updating dataProvider endpoint map...');

    const resolvedDataProviderPath =
      this.dataProviderPath ?? this.projectPathResolver.resolveDashboardDataProviderPath();
    this.dataProviderPath = resolvedDataProviderPath;

    if (!resolvedDataProviderPath) {
      console.warn('⚠️ Could not locate dataProvider.ts. Skipping data provider updates.');
      console.warn('   Configure config.paths.dataProvider if your provider lives outside the default structure.');
      return;
    }

    if (!fs.existsSync(resolvedDataProviderPath)) {
      console.warn(`⚠️ dataProvider file not found at ${resolvedDataProviderPath}. Skipping update.`);
      console.warn('   Configure config.paths.dataProvider if your provider lives outside the default structure.');
      return;
    }

    let content = fs.readFileSync(resolvedDataProviderPath, 'utf-8');

    // Find the endpointMap object
    const endpointMapRegex = /const endpointMap:\s*Record<string,\s*string>\s*=\s*\{([\s\S]*?)\n\s*\};/;
    const match = content.match(endpointMapRegex);

    if (!match) {
      console.log('⚠️ Could not find endpointMap in dataProvider');
      return;
    }

    const existingContent = match[1];

    // Extract custom endpoints
    const customEndpoints = this.dataProviderGenerator.extractCustomEndpoints(existingContent ?? '');

    // Generate new API mappings

    const autoGeneratedMappings = this.dataProviderGenerator.generateEndpointMappings(
      this.models,
      getResourceName,
      (modelName) => this.controllerGenerator.getApiEndpoint(modelName),
    );

    // Build the new endpoint map
    const updatedEndpointMap = this.dataProviderGenerator.buildEndpointMap(autoGeneratedMappings, customEndpoints);

    content = content.replace(endpointMapRegex, updatedEndpointMap);
    fs.writeFileSync(resolvedDataProviderPath, content);
    console.log('✅ Updated dataProvider endpoint map');
  }

  private updateModule(model: PrismaModel): void {
    if (!model.modulePath) {
      console.log(`⚠️ No module path for ${model.name}`);
      return;
    }

    const moduleFileName = this.modulePathResolver.getModuleFileName(model.modulePath);
    if (!moduleFileName) {
      console.log(`⚠️ Module file not found in: ${model.modulePath}`);
      console.log(`📄 Creating module file for ${model.name}...`);
      const moduleFilePath = this.createModuleFile(model, model.modulePath);
      this.autoCreatedModules.push({
        name: model.name,
        moduleType: model.moduleType ?? 'features',
        moduleFilePath,
      });
      return;
    }

    const modulePath = path.join(model.modulePath, moduleFileName);
    let moduleContent = fs.readFileSync(modulePath, 'utf-8');
    const modelNameLower = toCamelCase(model.name);
    const controllerClassName = `${model.name}${this.namingSuffix}Controller`;
    const serviceClassName = `${model.name}${this.namingSuffix}Service`;

    const { controllerImport, serviceImport } = this.moduleUpdater.generateModuleImportStatements(
      model.name,
      modelNameLower,
      this.namingSuffix,
      this.fileSuffix,
    );

    if (!moduleContent.includes(controllerClassName)) {
      moduleContent = this.moduleUpdater.addImportsToModule(moduleContent, [controllerImport, serviceImport]);
    }

    moduleContent = this.moduleUpdater.addToArrayInModule(moduleContent, 'controllers', [controllerClassName]);
    moduleContent = this.moduleUpdater.addToArrayInModule(moduleContent, 'providers', [serviceClassName]);

    // Ensure PrismaService is imported and registered as a provider
    if (!moduleContent.includes('PrismaService')) {
      const prismaServiceAbsPath = path.join(this.workspaceRoot, this.config.input.prisma.servicePath as string);
      let prismaImportPath = path
        .relative(model.modulePath, prismaServiceAbsPath)
        .replace(/\\/g, '/')
        .replace(/\.ts$/, '');
      if (!prismaImportPath.startsWith('.')) {
        prismaImportPath = './' + prismaImportPath;
      }
      const prismaImport = `import { PrismaService } from '${prismaImportPath}';`;
      moduleContent = this.moduleUpdater.addImportsToModule(moduleContent, [prismaImport]);
      moduleContent = this.moduleUpdater.addToArrayInModule(moduleContent, 'providers', ['PrismaService']);
    }

    fs.writeFileSync(modulePath, moduleContent);
    console.log(`✅ Updated module: ${modulePath}`);
  }

  private withFileSuffix(baseName: string): string {
    return this.fileSuffix ? `${baseName}.${this.fileSuffix}` : baseName;
  }

  async generate(): Promise<void> {
    console.log('🚀 Starting API generation...');

    try {
      await this.generateNestStaticFiles();
      this.parseSchema();
      await this.findModules();
      await this.generateFullNestModule();
      this.updateAppModule(this.autoCreatedModules);
      if (this.config.output.dashboard.updateDataProvider as boolean) {
        this.updateDataProvider();
      }
      console.log('✅ API generation completed successfully!');
    } catch (error) {
      console.error('❌ Error during API generation:', error);
      throw error;
    }
  }
}
