import type { PrismaModel, PrismaField } from '@tg-scripts/types';
import { tagAutoGenerated, toCamelCase } from '../utils';
import type { IGenerator } from '@tg-scripts/types';
import {
  getList,
  getOne,
  getMany,
  getManyReference,
  create,
  update,
  updateMany,
  deleteOne,
  deleteMany,
  getSelectFields,
  getImportStatements,
} from './config';

export type NestServiceGeneratorOptions = {
  excludeFields?: string[] | undefined;
  suffix?: string | undefined;
  serviceFilePath?: string;
  dtosPath?: string;
  utilsPath?: string;
  workspaceRoot?: string;
  prismaServicePath?: string;
  models?: PrismaModel[];
  relationsInclude?: 'all' | string[];
};

export class NestServiceGenerator implements IGenerator<PrismaModel, string> {
  private fileSuffix: string;
  private namingSuffix: string;
  constructor(options: NestServiceGeneratorOptions) {
    this.fileSuffix = options.suffix ? options.suffix.toLowerCase() : '';
    this.namingSuffix = options.suffix
      ? options.suffix.charAt(0).toUpperCase() + options.suffix.slice(1).toLowerCase()
      : '';
  }
  public generate(model: PrismaModel, options?: NestServiceGeneratorOptions): string {
    const { name, fields } = model;
    const pascalCaseName = name;
    const camelCaseName = toCamelCase(name);
    // Fields to check for uniqueness before creating (uniqueChecks)
    const uniqueFields = fields.filter((f) => f.isUnique);
    const excludedFields = options?.excludeFields || [];
    // Fields to be returned in the response
    const selectFields = fields.filter((f) => !excludedFields.includes(f.name) && !f.isRelation).map((f) => f.name);
    // Fields to be searched in the database
    // Use searchType computed during parsing (handles Json/relations exclusion and correct type mapping)
    const searchableFields = fields
      .filter((f) => !excludedFields.includes(f.name))
      .map((f) => {
        const searchType = f.searchType;
        return searchType ? `{ name: '${f.name}', type: '${searchType}' }` : null;
      })
      .filter((field) => field !== null)
      .join(', ');

    // Use defaultSortBy computed during parsing (prefers timestamp, then createdAt, then id)
    const defaultSortBy = model.defaultSortBy || 'id';

    const uniqueGetters = uniqueFields
      .map((f) => {
        const methodName = `getOneBy${f.name.charAt(0).toUpperCase()}${f.name.slice(1)}`;
        return `
  async ${methodName}(value: any) {
    const item = await this.prisma.${camelCaseName}.findUnique({
      where: { ${f.name}: value },
      select: this.getSelectFields(),
    });
    if (!item) {
      throw new NotFoundException('${pascalCaseName} not found');
    }
    return item;
  }
`; // value typed as any here; could be improved by mapping field baseType to TS type
      })
      .join('\n');

    const content = tagAutoGenerated(
      `
${getImportStatements(pascalCaseName, camelCaseName, uniqueFields?.length > 0, this.fileSuffix, this.namingSuffix, options)}

@Injectable()
export class ${pascalCaseName}${this.namingSuffix}Service {
  constructor(private readonly prisma: PrismaService) {}

  ${getList(camelCaseName, searchableFields, defaultSortBy)}
  ${getOne(pascalCaseName, camelCaseName)}
  ${getMany(camelCaseName)}
  ${getManyReference(camelCaseName, searchableFields, defaultSortBy)}
  ${create(pascalCaseName, camelCaseName, uniqueFields, this.namingSuffix)}
  ${update(pascalCaseName, camelCaseName, uniqueFields, this.namingSuffix)}
  ${updateMany(pascalCaseName, this.namingSuffix)}
  ${deleteOne(pascalCaseName, camelCaseName)}
  ${deleteMany()}
  ${getSelectFields(selectFields, this.buildRelationSelects(model, options))}
  ${uniqueGetters}
}
`,
      pascalCaseName,
    );

    return content;
  }

  private buildRelationSelects(model: PrismaModel, options?: NestServiceGeneratorOptions): string[] {
    const includeSetting = options?.relationsInclude;
    if (!includeSetting || (Array.isArray(includeSetting) && includeSetting.length === 0)) {
      return [];
    }

    const includeAll = includeSetting === 'all';
    const includeList = Array.isArray(includeSetting) ? includeSetting : [];
    const modelsByName = new Map(options?.models?.map((m) => [m.name, m]));

    return model.fields
      .filter((field) => field.isRelation && (includeAll || includeList.includes(field.name)))
      .map((field) => this.buildRelationSelect(field, modelsByName));
  }

  private buildRelationSelect(field: PrismaField, modelsByName?: Map<string, PrismaModel | undefined>): string {
    const targetModel = modelsByName?.get(field.baseType);
    const displayField = targetModel?.displayField ?? targetModel?.tgLabelField ?? 'id';
    const selectFields = new Set<string>(['id']);
    if (displayField) {
      selectFields.add(displayField);
    }

    const selectBody = Array.from(selectFields)
      .map((name) => `${name}: true`)
      .join(', ');

    return `${field.name}: { select: { ${selectBody} } }`;
  }
}
