import type { PrismaModel } from '@tg-scripts/types';
import { tagAutoGenerated, toCamelCase } from '../utils';
import type { IGenerator } from '@tg-scripts/types';
import {
  getList,
  getOne,
  getMany,
  getManyReference,
  create,
  update,
  updateMany,
  deleteOne,
  deleteMany,
  getSelectFields,
  getImportStatements,
} from './config';

export type NestServiceGeneratorOptions = {
  excludeFields?: string[] | undefined;
  suffix?: string | undefined;
  serviceFilePath?: string;
  dtosPath?: string;
  utilsPath?: string;
  workspaceRoot?: string;
  prismaServicePath?: string;
};

export class NestServiceGenerator implements IGenerator<PrismaModel, string> {
  private fileSuffix: string;
  private namingSuffix: string;
  constructor(options: NestServiceGeneratorOptions) {
    this.fileSuffix = options.suffix ? options.suffix.toLowerCase() : '';
    this.namingSuffix = options.suffix
      ? options.suffix.charAt(0).toUpperCase() + options.suffix.slice(1).toLowerCase()
      : '';
  }
  public generate(model: PrismaModel, options?: NestServiceGeneratorOptions): string {
    const { name, fields } = model;
    const pascalCaseName = name;
    const camelCaseName = toCamelCase(name);
    // Fields to check for uniqueness before creating (uniqueChecks)
    const uniqueFields = fields.filter((f) => f.isUnique);
    const excludedFields = options?.excludeFields || [];
    // Fields to be returned in the response
    const selectFields = fields.filter((f) => !excludedFields.includes(f.name)).map((f) => f.name);
    // Fields to be searched in the database
    // Use searchType computed during parsing (handles Json/relations exclusion and correct type mapping)
    const searchableFields = fields
      .filter((f) => !excludedFields.includes(f.name))
      .map((f) => {
        const searchType = f.searchType;
        return searchType ? `{ name: '${f.name}', type: '${searchType}' }` : null;
      })
      .filter((field) => field !== null)
      .join(', ');

    // Use defaultSortBy computed during parsing (prefers timestamp, then createdAt, then id)
    const defaultSortBy = model.defaultSortBy || 'id';

    const content = tagAutoGenerated(
      `
${getImportStatements(pascalCaseName, camelCaseName, uniqueFields?.length > 0, this.fileSuffix, this.namingSuffix, options)}

@Injectable()
export class ${pascalCaseName}${this.namingSuffix}Service {
  constructor(private readonly prisma: PrismaService) {}

  ${getList(camelCaseName, searchableFields, defaultSortBy)}
  ${getOne(pascalCaseName, camelCaseName)}
  ${getMany(camelCaseName)}
  ${getManyReference(camelCaseName, searchableFields, defaultSortBy)}
  ${create(pascalCaseName, camelCaseName, uniqueFields, this.namingSuffix)}
  ${update(pascalCaseName, camelCaseName, uniqueFields, this.namingSuffix)}
  ${updateMany(pascalCaseName, this.namingSuffix)}
  ${deleteOne(pascalCaseName, camelCaseName)}
  ${deleteMany()}
  ${getSelectFields(selectFields)}
}
`,
      pascalCaseName,
    );

    return content;
  }
}
