import type { PrismaModel } from '@tg-scripts/types';

type EndpointResolver = (modelName: string) => string;

export class DataProviderEndpointGenerator {
  public extractCustomEndpoints(content: string): string {
    const customEndpointsMatch = content.split(/\/\/\s*Auto-generated API endpoints/);

    if (customEndpointsMatch.length > 1) {
      const afterAutoGen = customEndpointsMatch[customEndpointsMatch.length - 1];
      const customMatch = afterAutoGen?.match(/\/\/\s*Custom endpoints([\s\S]*)/);
      if (customMatch) {
        return (
          customMatch[1]
            ?.split('\n')
            .filter((line) => {
              const trimmed = line.trim();
              return trimmed && !trimmed.startsWith('//') && trimmed !== '';
            })
            .join('\n') ?? ''
        );
      }
      return '';
    }

    return content
      .split('\n')
      .filter((line) => {
        const trimmed = line.trim();
        return trimmed && !trimmed.startsWith('//') && trimmed !== '';
      })
      .join('\n');
  }

  public generateEndpointMappings(
    models: PrismaModel[],
    getResourceName: EndpointResolver,
    getApiEndpoint: EndpointResolver,
  ): string {
    return models
      .filter((model) => model.modulePath)
      .map((model) => {
        const resourceName = getResourceName(model.name);
        const apiEndpoint = getApiEndpoint(model.name);
        return `    '${resourceName}': '${apiEndpoint}'`;
      })
      .join(',\n');
  }

  public buildEndpointMap(autoGeneratedMappings: string, customEndpoints: string): string {
    let endpointMap = `const endpointMap: Record<string, string> = {\n`;
    endpointMap += `    // Auto-generated API endpoints\n`;

    if (autoGeneratedMappings.trim()) {
      endpointMap += autoGeneratedMappings;
    }

    if (customEndpoints.trim()) {
      if (autoGeneratedMappings.trim()) {
        endpointMap += `,\n    // Custom endpoints\n${customEndpoints}`;
      } else {
        endpointMap += customEndpoints;
      }
    }

    endpointMap += `\n  };`;
    return endpointMap;
  }
}
