import { NestAppModuleParser } from '../parser/nest-app-module-parser/NestAppModuleParser';

describe('NestAppModuleParser', () => {
  const parser = new NestAppModuleParser();
  describe('Find Module Decorator Bounds', () => {
    it('should find module decorator bounds', () => {
      const content = `@Module({
  imports: [],
  controllers: [AppController]
})`;
      const result = parser.parse(content);

      expect(result).not.toBeNull();
      expect(result?.moduleBounds?.start).toBeGreaterThan(-1);
      expect(result?.moduleBounds?.end).toBeGreaterThan(result.moduleBounds!.start);
    });

    it('should return null if decorator not found', () => {
      const content = `export class AppModule {}`;
      const result = parser.parse(content);

      expect(result.moduleBounds).toBeNull();
    });

    it('should handle nested structures', () => {
      const content = `@Module({
  imports: [{ provide: APP_INTERCEPTOR, useClass: AuditInterceptor }],
  controllers: [AppController]
})`;
      const result = parser.parse(content);

      expect(result.moduleBounds).not.toBeNull();
    });

    it('should return null if braces are unbalanced', () => {
      const content = `@Module({
  imports: []`;
      const result = parser.parse(content);

      expect(result.moduleBounds).toBeNull();
    });
  });

  describe('Find Imports Array Bounds', () => {
    it('should find imports array bounds', () => {
      const content = `@Module({
  imports: [ConfigModule, UserModule],
  controllers: [AppController]
})`;
      const result = parser.parse(content);

      expect(result.importsBounds).not.toBeNull();
      expect(result.importsBounds?.start).toBeGreaterThan(-1);
      expect(result.importsBounds?.end).toBeGreaterThan(result.importsBounds!.start);
    });

    it('should return null if imports keyword not found', () => {
      const content = `@Module({
  controllers: [AppController]
})`;
      const result = parser.parse(content);

      expect(result.importsBounds).toBeNull();
    });

    it('should return null if brackets not found', () => {
      const content = `@Module({
  imports:
  controllers: [AppController]
})`;
      const result = parser.parse(content);

      expect(result.importsBounds).toBeNull();
    });

    it('should return null if module brace is unmatched', () => {
      const content = `@Module({
  imports: [ConfigModule]`;
      const result = parser.parse(content);

      expect(result.importsBounds).toBeNull();
    });

    it('should return null if imports array bracket is unmatched', () => {
      const content = `@Module({
  imports: [ConfigModule
})`;
      const result = parser.parse(content);

      expect(result.importsBounds).toBeNull();
    });
  });

  describe('extractAutoGeneratedModules', () => {
    it('should extract module names from block', () => {
      const content = `@Module({  imports: [
      // AUTO-GENERATED MODULES START
      UserModule,
      AuthModule,
      // AUTO-GENERATED MODULES END
    ]
  })`;
      const result = parser.parse(content);

      expect(result.tokens).toContain('UserModule');
      expect(result.tokens).toContain('AuthModule');
      expect(result.tokens.length).toBe(2);
    });

    it('should handle empty block', () => {
      const content = `@Module({  imports: [
      // AUTO-GENERATED MODULES START
    // AUTO-GENERATED MODULES END
    ]
  })`;
      const result = parser.parse(content);

      expect(result.tokens).toEqual([]);
    });

    it('should return empty array if block not found', () => {
      const content = `UserModule, AuthModule`;
      const result = parser.parse(content);

      expect(result.tokens).toEqual([]);
    });

    it('should handle modules with different spacing', () => {
      const content = `@Module({  imports: [
      // AUTO-GENERATED MODULES START
    CustomFieldTypeModule,
    ProjectInstanceModule,
    // AUTO-GENERATED MODULES END
    ]
  })`;
      const result = parser.parse(content);

      expect(result.tokens).toContain('CustomFieldTypeModule');
      expect(result.tokens).toContain('ProjectInstanceModule');
      expect(result.tokens.length).toBe(2);
    });
  });
});
