import type { PrismaModel, Guard } from '@tg-scripts/types';
import type { IGenerator } from '@tg-scripts/types';
import { tagAutoGenerated, pluralize, toKebabCase, toCamelCase } from '../utils';
import {
  deleteOne,
  getManyReference,
  getOne,
  updateMany,
  update,
  create,
  deleteMany,
  getMany,
  getList,
  getControllerImportStatements,
} from './config';
import { GuardResolver } from './GuardResolver';

export type NestControllerGeneratorOptions = {
  suffix?: string | undefined;
  isAdmin?: boolean;
  guards?: Guard[];
  guardsEnabled?: boolean;
};

export type NestControllerGeneratorInput = {
  model: PrismaModel;
};

export class NestControllerGenerator implements IGenerator<NestControllerGeneratorInput, string> {
  private baseRoute: string;
  private fileSuffix: string;
  private guardResolver: GuardResolver;
  private isAdmin: boolean;
  private namingSuffix: string;
  constructor(options: NestControllerGeneratorOptions) {
    this.baseRoute = options.suffix ? `${options.suffix.toLowerCase()}-api` : 'tg-api';
    this.fileSuffix = options.suffix ? options.suffix.toLowerCase() : '';
    this.namingSuffix = options.suffix
      ? options.suffix.charAt(0).toUpperCase() + options.suffix.slice(1).toLowerCase()
      : '';
    this.isAdmin = options.isAdmin ?? false;
    this.guardResolver = new GuardResolver(options.guards || [], options.guardsEnabled ?? true);
  }

  public generate(input: NestControllerGeneratorInput): string {
    const { model } = input;
    const { name } = model;
    const pascalCaseName = name;
    const camelCaseName = toCamelCase(name);
    const apiEndpoint = this.getApiEndpoint(name);
    const guardImports = this.guardResolver.generateImports().join('\n');
    const includeUseGuards = !this.isAdmin && this.guardResolver.isEnabled() && this.guardResolver.hasGuards();
    const guardDecorator = this.isAdmin
      ? '@IsAdmin()'
      : includeUseGuards
        ? this.guardResolver.generateUseGuardsDecorator()
        : '';

    const content = tagAutoGenerated(
      `
${getControllerImportStatements({
  pascalCaseName,
  camelCaseName,
  fileSuffix: this.fileSuffix,
  namingSuffix: this.namingSuffix,
  isAdmin: this.isAdmin,
  guardImports,
  includeUseGuards,
})}

@ApiTags('${this.namingSuffix} ${this.isAdmin ? 'Admin' : ''} Controller for ${pascalCaseName}')
@Controller('${apiEndpoint}')
${guardDecorator}
export class ${pascalCaseName}${this.namingSuffix}Controller {
  constructor(private readonly ${camelCaseName}${this.namingSuffix}Service: ${pascalCaseName}${this.namingSuffix}Service) {}

  ${getList(pascalCaseName, camelCaseName, this.namingSuffix)}
  ${getMany(pascalCaseName, camelCaseName, this.namingSuffix)}
  ${getManyReference(pascalCaseName, camelCaseName, this.namingSuffix)}
  ${getOne(pascalCaseName, camelCaseName, this.namingSuffix)}
  ${create(pascalCaseName, camelCaseName, this.namingSuffix)}
  ${update(pascalCaseName, camelCaseName, this.namingSuffix)}
  ${updateMany(pascalCaseName, camelCaseName, this.namingSuffix)}
  ${deleteOne(pascalCaseName, camelCaseName, this.namingSuffix)}
  ${deleteMany(pascalCaseName, camelCaseName, this.namingSuffix)}
}
`,
      pascalCaseName,
    );

    return content;
  }

  /**
   * Get the API endpoint path for a model
   * Uses kebab-case with plural form
   * Example: CustomFieldType -> custom-field-types
   */
  public getApiEndpoint(modelName: string): string {
    const kebab = toKebabCase(modelName);
    const plural = pluralize(kebab);
    return `${this.baseRoute}/${plural}`;
  }
}
