import type { PrismaModel, Guard, AdapterDefinition } from '@tg-scripts/types';
import type { IGenerator } from '@tg-scripts/types';
import { tagAutoGenerated, pluralize, toKebabCase, toCamelCase } from '../utils';
import {
  deleteOne,
  getManyReference,
  getOne,
  updateMany,
  update,
  create,
  deleteMany,
  getMany,
  getList,
  getControllerImportStatements,
} from './config';
import { GuardResolver } from './GuardResolver';
import { generateAdapterEndpoint, generateAdapterImports, generateAdapterGuardImports } from './adapter-config';

export type NestControllerGeneratorOptions = {
  suffix?: string | undefined;
  isAdmin?: boolean;
  guards?: Guard[];
  guardsEnabled?: boolean;
  prefix?: string | undefined;
  dtosPath?: string | undefined;
  workspaceRoot?: string | undefined;
};

export type NestControllerGeneratorInput = {
  model: PrismaModel;
  adapters?: AdapterDefinition[];
};

export class NestControllerGenerator implements IGenerator<NestControllerGeneratorInput, string> {
  private baseRoute: string;
  private fileSuffix: string;
  private guardResolver: GuardResolver;
  private isAdmin: boolean;
  private namingSuffix: string;
  constructor(options: NestControllerGeneratorOptions) {
    this.baseRoute = options.prefix?.trim()
      ? options.prefix.trim()
      : options.suffix
        ? `${options.suffix.toLowerCase()}-api`
        : 'tg-api';
    this.fileSuffix = options.suffix ? options.suffix.toLowerCase() : '';
    this.namingSuffix = options.suffix
      ? options.suffix.charAt(0).toUpperCase() + options.suffix.slice(1).toLowerCase()
      : '';
    this.isAdmin = options.isAdmin ?? false;
    this.guardResolver = new GuardResolver(options.guards || [], options.guardsEnabled ?? true);
  }

  public generate(input: NestControllerGeneratorInput): string {
    const { model, adapters = [] } = input;
    const { name } = model;
    const pascalCaseName = name;
    const camelCaseName = toCamelCase(name);
    const apiEndpoint = this.getApiEndpoint(name);
    const guardImports = this.guardResolver.generateImports().join('\n');
    const includeUseGuards = !this.isAdmin && this.guardResolver.isEnabled() && this.guardResolver.hasGuards();
    const guardDecorator = this.isAdmin
      ? '@IsAdmin()'
      : includeUseGuards
        ? this.guardResolver.generateUseGuardsDecorator()
        : '';

    // Generate adapter endpoints
    const adapterEndpoints = adapters
      .map((adapter) => generateAdapterEndpoint(adapter, model, this.namingSuffix))
      .join('\n');

    // Generate adapter imports
    const adapterImportLines = adapters.length > 0 ? generateAdapterImports(adapters).join('\n') : '';

    const adapterGuardImports = adapters.length > 0 ? generateAdapterGuardImports(adapters).join('\n') : '';

    // Combine all imports
    const allGuardImports = [guardImports, adapterGuardImports].filter((i) => i.trim().length > 0).join('\n');

    // Conditionally inject PrismaService only if adapters are present
    const constructorParams =
      adapters.length > 0
        ? `private readonly ${camelCaseName}${this.namingSuffix}Service: ${pascalCaseName}${this.namingSuffix}Service,
    private readonly prisma: PrismaService`
        : `private readonly ${camelCaseName}${this.namingSuffix}Service: ${pascalCaseName}${this.namingSuffix}Service`;

    const content = tagAutoGenerated(
      `
${getControllerImportStatements({
  pascalCaseName,
  camelCaseName,
  fileSuffix: this.fileSuffix,
  namingSuffix: this.namingSuffix,
  isAdmin: this.isAdmin,
  guardImports: allGuardImports,
  includeUseGuards,
  hasAdapters: adapters.length > 0,
})}

${adapterImportLines}

@ApiTags('${this.namingSuffix} ${this.isAdmin ? 'Admin' : ''} Controller for ${pascalCaseName}')
@Controller('${apiEndpoint}')
${guardDecorator}
export class ${pascalCaseName}${this.namingSuffix}Controller {
  constructor(
    ${constructorParams}
  ) {}

  ${getList(pascalCaseName, camelCaseName, this.namingSuffix)}
  ${getMany(pascalCaseName, camelCaseName, this.namingSuffix)}
  ${getManyReference(pascalCaseName, camelCaseName, this.namingSuffix)}
  ${getOne(pascalCaseName, camelCaseName, this.namingSuffix)}
  ${create(pascalCaseName, camelCaseName, this.namingSuffix)}
  ${update(pascalCaseName, camelCaseName, this.namingSuffix)}
  ${updateMany(pascalCaseName, camelCaseName, this.namingSuffix)}
  ${deleteOne(pascalCaseName, camelCaseName, this.namingSuffix)}
  ${deleteMany(pascalCaseName, camelCaseName, this.namingSuffix)}
  ${adapterEndpoints}
}
`,
      pascalCaseName,
    );

    return content;
  }

  /**
   * Get the API endpoint path for a model
   * Uses kebab-case with plural form
   * Example: CustomFieldType -> custom-field-types
   */
  public getApiEndpoint(modelName: string): string {
    const kebab = toKebabCase(modelName);
    const plural = pluralize(kebab);
    return `${this.baseRoute}/${plural}`;
  }
}
