import type { IGenerator } from '@tg-scripts/types';
import type { PrismaModel } from '@tg-scripts/types';
import type { GeneratorOptions } from '@tg-scripts/types';
import type { AdapterDefinition } from '../../types/adapter';
import { toCamelCase } from '../utils';
import { tagAutoGenerated } from '../utils/auto-text';
import { generateAdapterEndpoint, generateAdapterImports } from './adapter-config';

export interface NestAdapterControllerGeneratorInput {
  model: PrismaModel;
  adapters: AdapterDefinition[];
}

export class NestAdapterControllerGenerator
  implements IGenerator<NestAdapterControllerGeneratorInput, string>
{
  private fileSuffix: string;
  private namingSuffix: string;

  constructor(options: GeneratorOptions) {
    this.fileSuffix = options.suffix ? options.suffix.toLowerCase() : '';
    this.namingSuffix = options.suffix
      ? options.suffix.charAt(0).toUpperCase() + options.suffix.slice(1).toLowerCase()
      : '';
  }

  public generate(input: NestAdapterControllerGeneratorInput): string {
    const { model, adapters = [] } = input;

    if (adapters.length === 0) {
      return ''; // No adapters, no controller
    }

    const pascalCaseName = model.name;
    const camelCaseName = toCamelCase(model.name);

    console.log(`[Adapter Controller Generator] Generating adapter controller for ${pascalCaseName} with ${adapters.length} adapters`);

    // Generate adapter endpoints
    const adapterEndpoints = adapters
      .map((adapter) => generateAdapterEndpoint(adapter, model, this.namingSuffix))
      .join('\n\n');

    // Generate adapter imports
    const adapterImportLines = generateAdapterImports(adapters, model).join('\n');

    // Check if any decorators are needed
    const needsPost = adapters.some(a => a.config.method === 'POST');
    const needsGet = adapters.some(a => a.config.method === 'GET');
    const needsPut = adapters.some(a => a.config.method === 'PUT');
    const needsPatch = adapters.some(a => a.config.method === 'PATCH');
    const needsDelete = adapters.some(a => a.config.method === 'DELETE');

    const methodDecorators: string[] = [];
    if (needsGet) methodDecorators.push('Get');
    if (needsPost) methodDecorators.push('Post');
    if (needsPut) methodDecorators.push('Put');
    if (needsPatch) methodDecorators.push('Patch');
    if (needsDelete) methodDecorators.push('Delete');

    const decoratorImports = methodDecorators.length > 0 
      ? `import { ${methodDecorators.join(', ')}, Body, Query, Param } from '@nestjs/common';`
      : `import { Body, Query, Param } from '@nestjs/common';`;

    const content = tagAutoGenerated(
      `
${adapterImportLines}
${decoratorImports}
import { Controller } from '@nestjs/common';
import { ApiTags, ApiOperation, ApiResponse } from '@nestjs/swagger';
import { ${pascalCaseName}${this.namingSuffix}Service } from './${camelCaseName}${this.fileSuffix ? '.' + this.fileSuffix : ''}.service';
import { PrismaService } from '@/infrastructure/database/prisma.service';

@ApiTags('${pascalCaseName} Custom Adapters')
@Controller()
export class ${pascalCaseName}AdaptersController {
  constructor(
    private readonly ${camelCaseName}${this.namingSuffix}Service: ${pascalCaseName}${this.namingSuffix}Service,
    private readonly prisma: PrismaService,
  ) {}

${adapterEndpoints}
}
`,
      pascalCaseName,
    );

    return content;
  }
}

