import type { PrismaModel } from '@tg-scripts/types';
import type { IGenerator } from '@tg-scripts/types';
import { tagAutoGenerated, pluralize, toKebabCase, toCamelCase } from '../utils';
import {
  deleteOne,
  getManyReference,
  getOne,
  updateMany,
  update,
  create,
  deleteMany,
  getMany,
  getList,
  getControllerImportStatements,
} from './config';

export type NestControllerGeneratorOptions = {
  suffix?: string | undefined;
  isAdmin?: boolean;
};

export type NestControllerGeneratorInput = {
  model: PrismaModel;
};

export class NestControllerGenerator implements IGenerator<NestControllerGeneratorInput, string> {
  private baseRoute: string;
  private fileSuffix: string;
  private namingSuffix: string;
  private isAdmin: boolean;
  constructor(options: NestControllerGeneratorOptions) {
    this.baseRoute = options.suffix ? `${options.suffix.toLowerCase()}-api` : 'tg-api';
    this.fileSuffix = options.suffix ? options.suffix.toLowerCase() : '';
    this.namingSuffix = options.suffix
      ? options.suffix.charAt(0).toUpperCase() + options.suffix.slice(1).toLowerCase()
      : '';
    this.isAdmin = options.isAdmin ?? false;
  }

  public generate(input: NestControllerGeneratorInput): string {
    const { model } = input;
    const { name } = model;
    const pascalCaseName = name;
    const camelCaseName = toCamelCase(name);
    const apiEndpoint = this.getApiEndpoint(name);

    const content = tagAutoGenerated(
      `
${getControllerImportStatements(pascalCaseName, camelCaseName, this.fileSuffix, this.namingSuffix, this.isAdmin)}

@ApiTags('${this.namingSuffix} ${this.isAdmin ? 'Admin' : ''} Controller for ${pascalCaseName}')
@Controller('${apiEndpoint}')
${this.isAdmin ? '@IsAdmin()' : ''}
export class ${pascalCaseName}${this.namingSuffix}Controller {
  constructor(private readonly ${camelCaseName}${this.namingSuffix}Service: ${pascalCaseName}${this.namingSuffix}Service) {}

  ${getList(pascalCaseName, camelCaseName, this.namingSuffix)}
  ${getMany(pascalCaseName, camelCaseName, this.namingSuffix)}
  ${getManyReference(pascalCaseName, camelCaseName, this.namingSuffix)}
  ${getOne(pascalCaseName, camelCaseName, this.namingSuffix)}
  ${create(pascalCaseName, camelCaseName, this.namingSuffix)}
  ${update(pascalCaseName, camelCaseName, this.namingSuffix)}
  ${updateMany(pascalCaseName, camelCaseName, this.namingSuffix)}
  ${deleteOne(pascalCaseName, camelCaseName, this.namingSuffix)}
  ${deleteMany(pascalCaseName, camelCaseName, this.namingSuffix)}
}
`,
      pascalCaseName,
    );

    return content;
  }

  /**
   * Get the API endpoint path for a model
   * Uses kebab-case with plural form
   * Example: CustomFieldType -> custom-field-types
   */
  public getApiEndpoint(modelName: string): string {
    const kebab = toKebabCase(modelName);
    const plural = pluralize(kebab);
    return `${this.baseRoute}/${plural}`;
  }
}
