export const tagAutoGenerated = (
  text: string,
  modelName?: string,
  generatorName?: string,
  addTimestamp: boolean = false,
) => {
  const lines: string[] = [
    '/**',
    ' * AUTO-GENERATED FILE',
    ` * This file was automatically generated${generatorName ? ` by the ${generatorName} generator` : ''}.`,
    ' * Do not edit this file manually. Instead, modify the Prisma schema and regenerate.',
  ];

  // Add model name line if provided (including empty string)
  if (modelName !== undefined) {
    lines.push(` * Generated from model: ${modelName}`);
  }

  // Add timestamp line if requested
  if (addTimestamp) {
    lines.push(` * Generated at: ${new Date().toISOString()}`);
  }

  lines.push(' */');
  lines.push(text);

  return lines.join('\n');
};
