import type { PrismaModel } from '@tg-scripts/types';
import { tagAutoGenerated } from '../../utils';
import {
  FormComponentRelationField,
  FormComponentEnumField,
  FormComponentBooleanField,
  FormComponentNumberField,
  FormComponentDateTimeField,
  FormComponentJsonField,
  FormComponentBytesField,
  FormComponentUrlField,
  FormComponentEmailField,
  FormComponentPasswordField,
  FormComponentTelField,
  FormComponentStringField,
  FormComponentFileUploadField,
} from './components-config';
import type { ParsedSchema } from '@tg-scripts/types';

/**
 * Generate the content for an Edit component
 */
export function editPage(model: PrismaModel, parsedSchema: ParsedSchema<PrismaModel>): string {
  const { models, enums } = parsedSchema;
  const componentName = `${model.name}Edit`;
  // Filter fields for Edit: exclude ids, timestamps, arrays, and FK scalar fields we will represent via ReferenceInput
  const fields = model.fields.filter(
    (f) =>
      !f.isId && f.name !== 'createdAt' && f.name !== 'updatedAt' && !f.isArray && (!f.foreignKeyName || f.isRelation),
  );

  // Determine which components are actually needed
  const usedComponents = new Set(['Edit', 'SimpleForm']);
  fields.forEach((field) => {
    if (field.isRelation) {
      for (const component of FormComponentRelationField.components) {
        usedComponents.add(component);
      }
    }
    if (field.isEnum) {
      for (const component of FormComponentEnumField.components) {
        usedComponents.add(component);
      }
    }
    if (field.baseType === 'Boolean') {
      for (const component of FormComponentBooleanField.components) {
        usedComponents.add(component);
      }
    }
    if (['Int', 'Float', 'Decimal', 'BigInt'].includes(field.baseType)) {
      for (const component of FormComponentNumberField.components) {
        usedComponents.add(component);
      }
    }
    if (field.baseType === 'DateTime') {
      for (const component of FormComponentDateTimeField.components) {
        usedComponents.add(component);
      }
    }
    if (field.baseType === 'Json') {
      for (const component of FormComponentJsonField.components) {
        usedComponents.add(component);
      }
    }
    if (field.baseType === 'Bytes') {
      for (const component of FormComponentBytesField.components) {
        usedComponents.add(component);
      }
    }
    if (field.tgFormat === 'url') {
      for (const component of FormComponentUrlField.components) {
        usedComponents.add(component);
      }
    }
    if (field.tgFormat === 'email') {
      for (const component of FormComponentEmailField.components) {
        usedComponents.add(component);
      }
    }
    if (field.tgFormat === 'password') {
      for (const component of FormComponentPasswordField.components) {
        usedComponents.add(component);
      }
    }
    if (field.tgFormat === 'tel') {
      for (const component of FormComponentTelField.components) {
        usedComponents.add(component);
      }
    }
    if (field.tgUpload) {
      for (const component of FormComponentFileUploadField.components) {
        usedComponents.add(component);
      }
    }
    // Default string field
    if (!field.isRelation && !field.isEnum && field.baseType === 'String' && !field.tgFormat && !field.tgUpload) {
      for (const component of FormComponentStringField.components) {
        usedComponents.add(component);
      }
    }
  });

  const imports = Array.from(usedComponents).sort().join(', ');

  const component = `
import React from 'react';
import { ${imports} } from '@/components/admin';

export const ${componentName}: React.FC = () => (
  <Edit>
    <SimpleForm>
${fields
  .map((field) => {
    const relatedModel = models.find((m) => m.name === field.baseType);
    const enumValues = enums.get(field.baseType);
    if (field.isRelation) {
      return FormComponentRelationField.field(field, enumValues, relatedModel, model, models);
    }

    if (field.isEnum) {
      return FormComponentEnumField.field(field, enumValues);
    }

    if (field.baseType === 'Boolean') {
      return FormComponentBooleanField.field(field);
    }
    if (['Int', 'Float', 'Decimal', 'BigInt'].includes(field.baseType)) {
      return FormComponentNumberField.field(field);
    }
    if (field.baseType === 'DateTime') {
      return FormComponentDateTimeField.field(field);
    }
    if (field.baseType === 'Json') {
      return FormComponentJsonField.field(field);
    }
    if (field.baseType === 'Bytes') {
      return FormComponentBytesField.field(field);
    }
    if (field.tgFormat === 'url') {
      return FormComponentUrlField.field(field);
    }
    if (field.tgFormat === 'email') {
      return FormComponentEmailField.field(field);
    }
    if (field.tgFormat === 'password') {
      return FormComponentPasswordField.field(field);
    }
    if (field.tgFormat === 'tel') {
      return FormComponentTelField.field(field);
    }
    if (field.tgUpload) {
      return FormComponentFileUploadField.field(field);
    }
    return FormComponentStringField.field(field);
  })
  .join('\n')}
    </SimpleForm>
  </Edit>
);
`;

  return tagAutoGenerated(component, model.name, 'ReactComponentsGenerator');
}
