import { AdapterDefinition, IGenerator, PrismaModel } from '@tg-scripts/types';
import { AdapterParser } from '../../parser/adapter-parser/AdapterParser';
import { AdapterValidator } from '../../io/validation/AdapterValidator';
import { AdapterDtoGenerator } from '../adapter-dto-generator/AdapterDtoGenerator';
import * as path from 'path';
import * as fs from 'fs';
import { tagAutoGenerated } from '../utils/auto-text';
import { ModulePathResolver } from '../../io/module-path-resolver/ModulePathResolver';

export interface AdaptersGeneratorInput {
  models: PrismaModel[];
}

export interface AdaptersGeneratorOutput {
  [modelName: string]: {
    adapters: AdapterDefinition[];
    dtos: Array<{ path: string; content: string }>;
  };
}

export class AdaptersGenerator implements IGenerator<AdaptersGeneratorInput, AdaptersGeneratorOutput> {
  private workspaceRoot: string;
  constructor(
    private readonly adapterParser: AdapterParser,
    private readonly adapterValidator: AdapterValidator,
    private readonly adapterDtoGenerator: AdapterDtoGenerator,
    private readonly modulePathResolver: ModulePathResolver,
  ) {
    this.workspaceRoot = process.cwd();
  }

  public async generate(input: AdaptersGeneratorInput): Promise<AdaptersGeneratorOutput> {
    console.log('🔍 Generating adapters...');
    const result: AdaptersGeneratorOutput = {};
    for (const model of input.models) {
      let adapters: AdapterDefinition[] = [];
      let dtos: Array<{ path: string; content: string }> = [];

      const foundModule = this.modulePathResolver.findModulePath(model.name, process.cwd());

      if (foundModule) {
        model.modulePath = foundModule.path;
        model.moduleType = foundModule.type;
        console.log(`✅ Found module for ${model.name} in ${foundModule.type}/${foundModule.folderName}`);
      }

      if (!model.modulePath) {
        console.log(`⏭️ Skipping ${model.name} - no module path`);
        continue;
      }
      adapters = await this.adapterParser.parseAdapters(model, this.workspaceRoot);
      if (adapters.length > 0) {
        console.log(`📋 Found ${adapters.length} adapter(s) for ${model.name}`);

        // Validate adapters
        const validationErrors = this.adapterValidator.validateAll(adapters, model);
        if (validationErrors.length > 0) {
          console.error(`❌ Adapter validation errors for ${model.name}:`);
          validationErrors.forEach((err) => console.error(`   ${err.message}`));
          throw new Error(`Adapter validation failed for ${model.name}`);
        }
      }

      if (adapters.length > 0) {
        // Ensure adapters directory exists
        const adaptersDir = path.join(model.modulePath, 'adapters');
        fs.mkdirSync(adaptersDir, { recursive: true });

        // Generate adapter DTOs
        const adapterDtos = this.adapterDtoGenerator.generateAll(adapters, model.name);
        for (const [fileName, content] of adapterDtos) {
          const dtoPath = path.join(adaptersDir, fileName);
          dtos.push({ path: dtoPath, content: tagAutoGenerated(content, model.name) });
        }
      }
      result[model.name] = { adapters, dtos };
    }
    return result;
  }
}
