import type { PrismaModel } from '@tg-scripts/types';
import { tagAutoGenerated } from '../../utils';
import {
  ShowComponentRelationField,
  ShowComponentEnumField,
  ShowComponentDateTimeField,
  ShowComponentBooleanField,
  ShowComponentNumberField,
  ShowComponentJsonField,
  ShowComponentBytesField,
  ShowComponentUrlField,
  ShowComponentStringField,
} from './components-config';
import type { ParsedSchema } from '@tg-scripts/types';

/**
 * Generate the content for a Show component
 */
export function showPage(model: PrismaModel, parsedSchema: ParsedSchema<PrismaModel>): string {
  const { enums } = parsedSchema;
  const componentName = `${model.name}Show`;
  const fields = model.fields;

  // Determine which components are actually needed
  const usedComponents = new Set(['Show', 'SimpleShowLayout']);
  fields.forEach((field) => {
    if (field.isRelation) {
      for (const component of ShowComponentRelationField.components) {
        usedComponents.add(component);
      }
    }
    if (field.isEnum) {
      for (const component of ShowComponentEnumField.components) {
        usedComponents.add(component);
      }
    }
    if (field.baseType === 'DateTime') {
      for (const component of ShowComponentDateTimeField.components) {
        usedComponents.add(component);
      }
    }
    if (field.baseType === 'Boolean') {
      for (const component of ShowComponentBooleanField.components) {
        usedComponents.add(component);
      }
    }
    if (['Int', 'Float', 'Decimal', 'BigInt'].includes(field.baseType)) {
      for (const component of ShowComponentNumberField.components) {
        usedComponents.add(component);
      }
    }
    if (field.baseType === 'Json') {
      for (const component of ShowComponentJsonField.components) {
        usedComponents.add(component);
      }
    }
    if (field.baseType === 'Bytes') {
      for (const component of ShowComponentBytesField.components) {
        usedComponents.add(component);
      }
    }
    if (field.tgFormat === 'url') {
      for (const component of ShowComponentUrlField.components) {
        usedComponents.add(component);
      }
    }
    // String and other fields
    if (!field.isRelation && !field.isEnum && field.baseType === 'String' && field.tgFormat !== 'url') {
      for (const component of ShowComponentStringField.components) {
        usedComponents.add(component);
      }
      // Add ImageField if it's an image upload
      if (field.tgUpload === 'image') {
        usedComponents.add('ImageField');
      }
    }
  });

  const imports = Array.from(usedComponents).sort().join(', ');

  const component = `
import React from 'react';
import { ${imports} } from '@/components/admin';

export const ${componentName}: React.FC = () => (
  <Show>
    <SimpleShowLayout>
${fields
  .map((field) => {
    const enumValues = enums.get(field.baseType);
    if (field.isRelation) {
      return ShowComponentRelationField.field(field, enumValues);
    }

    if (field.isEnum) {
      return ShowComponentEnumField.field(field, enumValues);
    }

    if (field.baseType === 'DateTime') {
      return ShowComponentDateTimeField.field(field);
    }
    if (field.baseType === 'Boolean') {
      return ShowComponentBooleanField.field(field);
    }
    if (['Int', 'Float', 'Decimal', 'BigInt'].includes(field.baseType)) {
      return ShowComponentNumberField.field(field);
    }
    if (field.baseType === 'Json') {
      return ShowComponentJsonField.field(field);
    }
    if (field.baseType === 'Bytes') {
      return ShowComponentBytesField.field(field);
    }
    if (field.tgFormat === 'url') {
      return ShowComponentUrlField.field(field);
    }
    return ShowComponentStringField.field(field);
  })
  .join('\n')}
    </SimpleShowLayout>
  </Show>
);
`;

  return tagAutoGenerated(component, model.name, 'ReactComponentsGenerator');
}

