import * as fs from 'fs';
import * as path from 'path';
import type { Config, PrismaModel } from '@tg-scripts/types';
import { formatGeneratedFile } from '../../io/utils';
import { PrismaFieldParser } from '../../parser/prisma-field-parser/PrismaFieldParser';
import { PrismaRelationsParser } from '../../parser/prisma-relation-parser/PrismaRelationsParser';
import { PrismaSchemaParser } from '../../parser/prisma-schema-parser/PrismaSchemaParser';
import { tagAutoGenerated } from '../utils/auto-text';
import { NestDtoGenerator } from '../nest-dto-generator/NestDtoGenerator';

export class DtoGenerator {
  private readonly config: Config;
  private readonly dtoGenerator: NestDtoGenerator;
  private enums: Map<string, string[]> = new Map();
  private readonly fieldParser: PrismaFieldParser;
  private readonly fieldRelationsParser: PrismaRelationsParser;
  private models: PrismaModel[] = [];
  private readonly outputAbsolutePath: string;
  private readonly outputDir: string;
  private readonly schemaAbsolutePath: string;
  private readonly schemaParser: PrismaSchemaParser;
  private readonly schemaPath: string;
  private readonly workspaceRoot: string;
  constructor(config: Config) {
    this.config = config;
    this.workspaceRoot = process.cwd();
    this.schemaPath = config.input.prisma.schemaPath as string;
    this.schemaAbsolutePath = path.isAbsolute(this.schemaPath)
      ? this.schemaPath
      : path.join(this.workspaceRoot, this.schemaPath);
    this.outputDir = config.output.backend.dtosPath as string;
    this.outputAbsolutePath = path.isAbsolute(this.outputDir)
      ? this.outputDir
      : path.join(this.workspaceRoot, this.outputDir);
    this.fieldParser = new PrismaFieldParser();
    this.fieldRelationsParser = new PrismaRelationsParser();
    this.schemaParser = new PrismaSchemaParser(this.fieldParser, this.fieldRelationsParser);
    this.dtoGenerator = new NestDtoGenerator({ suffix: config.api.suffix as string });
  }

  private formatFiles(): void {
    console.log('🎨 Formatting generated files...');
    // Files are already formatted individually, but we format index.ts again for consistency
  }

  private generateDtos(): void {
    console.log('📝 Generating DTO files...');

    for (const model of this.models) {
      const content = this.dtoGenerator.generate({
        model,
        dtoType: 'response',
        enums: this.enums,
      });
      const taggedContent = tagAutoGenerated(content, model.name, 'DTO Generator');
      const fileName = `${model.name.toLowerCase()}-response.dto.ts`;
      const filePath = path.join(this.outputAbsolutePath, fileName);

      fs.writeFileSync(filePath, taggedContent);
      formatGeneratedFile(filePath, this.workspaceRoot);
      console.log(`✅ Generated ${fileName}`);
    }
  }

  private generateIndexFile(): void {
    console.log('📄 Generating index file...');
    const indexContent = this.models
      .map((model) => `export * from './${model.name.toLowerCase()}-response.dto';`)
      .join('\n');

    const taggedIndexContent = tagAutoGenerated(indexContent, undefined, 'DTO Generator');

    const indexFilePath = path.join(this.outputAbsolutePath, 'index.ts');
    fs.writeFileSync(indexFilePath, taggedIndexContent);
    formatGeneratedFile(indexFilePath, this.workspaceRoot);
    console.log('✅ Generated index.ts');
  }

  private parseSchema(): void {
    console.log('📖 Parsing Prisma schema...');
    console.log(`   Reading from: ${this.schemaAbsolutePath}`);

    const schemaContent = fs.readFileSync(this.schemaAbsolutePath, 'utf-8');
    console.log(`   Schema content length: ${schemaContent.length} characters`);

    this.schemaParser.load(schemaContent);
    const parsed = this.schemaParser.parse();

    this.models = parsed.models;
    this.enums = parsed.enums;

    if (this.models.length === 0) {
      console.warn('   ⚠️  Warning: No models found in schema!');
      console.warn('   ℹ️  Note: All models are included in DTO generation.');
    } else {
      this.models.forEach((model) => {
        console.log(`   📋 Found model: ${model.name}`);
      });
    }

    console.log(`📊 Found ${this.models.length} models in schema`);
  }

  private setupOutputDirectory(): void {
    const displayPath = this.toWorkspaceRelative(this.outputAbsolutePath);
    console.log(`📁 Setting up output directory at ${displayPath}...`);
    if (fs.existsSync(this.outputAbsolutePath)) {
      fs.rmSync(this.outputAbsolutePath, {
        recursive: true,
        force: true,
      });
    }
    fs.mkdirSync(this.outputAbsolutePath, { recursive: true });
  }

  private toWorkspaceRelative(targetPath: string): string {
    const relativePath = path.relative(this.workspaceRoot, targetPath);
    if (!relativePath || relativePath.startsWith('..')) {
      return targetPath;
    }

    return relativePath.replace(/\\/g, '/');
  }

  generate(): void {
    console.log('🚀 Starting DTO generation...');

    try {
      this.setupOutputDirectory();
      this.parseSchema();
      this.generateDtos();
      this.generateIndexFile();
      this.formatFiles();
      console.log('✅ DTO generation completed successfully!');
    } catch (error) {
      console.error('❌ Error during DTO generation:', error);
      throw error;
    }
  }
}
