import type { PrismaModel } from '@tg-scripts/types';
import { getResourceName, tagAutoGenerated } from '../../utils';
import {
  ListComponentRelationField,
  ListComponentEnumField,
  ListComponentDateTimeField,
  ListComponentBooleanField,
  ListComponentNumberField,
  ListComponentJsonField,
  ListComponentBytesField,
  ListComponentUrlField,
  ListComponentStringField,
} from './components-config';
import type { ParsedSchema } from '@tg-scripts/types';

/**
 * Generate the content for a List component
 */
export function listPage(model: PrismaModel, parsedSchema: ParsedSchema<PrismaModel>): string {
  const { models, enums } = parsedSchema;
  const componentName = `${model.name}List`;
  const fields = model.fields.filter((f) => !f.isId && !f.foreignKeyName);
  const resource = getResourceName(model.name);

  // Determine which components are actually needed
  const usedComponents = new Set(['List', 'DataTable']);
  fields.forEach((field) => {
    // Only add field components that are actually wrapped in DataTable.Col
    if (field.isRelation) {
      for (const component of ListComponentRelationField.components) {
        usedComponents.add(component);
      }
    }
    if (field.isEnum) {
      for (const component of ListComponentEnumField.components) {
        usedComponents.add(component);
      }
    }
    if (field.baseType === 'DateTime') {
      for (const component of ListComponentDateTimeField.components) {
        usedComponents.add(component);
      }
    }
    if (field.baseType === 'Boolean') {
      for (const component of ListComponentBooleanField.components) {
        usedComponents.add(component);
      }
    }
    if (['Int', 'Float', 'Decimal', 'BigInt'].includes(field.baseType)) {
      for (const component of ListComponentNumberField.components) {
        usedComponents.add(component);
      }
    }
    if (field.baseType === 'Json') {
      for (const component of ListComponentJsonField.components) {
        usedComponents.add(component);
      }
    }
    if (field.baseType === 'Bytes') {
      for (const component of ListComponentBytesField.components) {
        usedComponents.add(component);
      }
    }
    if (field.tgFormat === 'url') {
      for (const component of ListComponentUrlField.components) {
        usedComponents.add(component);
      }
    }
    // String and other fields
    if (!field.isRelation && !field.isEnum && field.baseType === 'String' && field.tgFormat !== 'url') {
      for (const component of ListComponentStringField.components) {
        usedComponents.add(component);
      }
    }
  });

  const imports = Array.from(usedComponents).sort().join(', ');

  const component = `
import React from 'react';
import { ${imports} } from '@/components/admin';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';

export const ${componentName}: React.FC = () => (
 <List>
   <div className="mb-2 flex justify-end">
     <Link to="/${resource}/studio">
       <Button variant="outline">Studio</Button>
     </Link>
   </div>
   <DataTable>
${fields
  .map((field) => {
    const relatedModel = models.find((m) => m.name === field.baseType);
    const enumValues = enums.get(field.baseType);
    if (field.isRelation) {
      return ListComponentRelationField.field(field, enumValues, relatedModel);
    }

    if (field.isEnum) {
      return ListComponentEnumField.field(field, enumValues);
    }

    if (field.baseType === 'DateTime') {
      return ListComponentDateTimeField.field(field);
    }
    if (field.baseType === 'Boolean') {
      return ListComponentBooleanField.field(field);
    }
    if (['Int', 'Float', 'Decimal', 'BigInt'].includes(field.baseType)) {
      return ListComponentNumberField.field(field);
    }
    if (field.baseType === 'Json') {
      return ListComponentJsonField.field(field);
    }
    if (field.baseType === 'Bytes') {
      return ListComponentBytesField.field(field);
    }
    if (field.tgFormat === 'url') {
      return ListComponentUrlField.field(field);
    }
    return ListComponentStringField.field(field);
  })
  .join('\n')}
     </DataTable>
   </List>
 );
 `;

  return tagAutoGenerated(component, model.name, 'ReactComponentsGenerator');
}
