import type { PrismaModel } from '@tg-scripts/types';
import { tagAutoGenerated } from '../../utils';
import type { ParsedSchema } from '@tg-scripts/types';

/**
 * Generate the content for a Studio component
 */
export function studioPage(model: PrismaModel, _parsedSchema: ParsedSchema<PrismaModel>): string {
  const componentName = `${model.name}Studio`;
  const fields = model.fields.filter((f) => !f.isId && f.name !== 'createdAt' && f.name !== 'updatedAt');
  // We rely on DataSheet to render editors via FieldFactory based on metadata
  const component = `
import React from 'react';
import { List } from '@/components/admin';
import { DataSheet } from '@/components/admin/data-sheet';

export const ${componentName}: React.FC = () => (
  <List title="${model.name} Studio">
    <DataSheet
      columns={[${fields.map((f) => `{ key: '${f.name}', header: '${f.name}' }`).join(', ')}]}
    />
  </List>
);
`;

  return tagAutoGenerated(component, model.name, 'ReactComponentsGenerator');
}

