source "https://rubygems.org"

gem "jekyll", "~> 4.2.0"
gem "just-the-docs", "0.7.0"
gem "webrick", "~> 1.8"

# GitHub Pages compatibility
group :jekyll_plugins do
  gem "jekyll-seo-tag", "~> 2.8"
  gem "jekyll-include-cache"
end

