import type { PrismaModel } from '@tg-scripts/types';

/**
 * Extract custom endpoints from endpointMap content
 */
export function extractCustomEndpoints(content: string): string {
  // Split by auto-generated section marker
  const customEndpointsMatch = content.split(/\/\/\s*Auto-generated API endpoints/);

  if (customEndpointsMatch.length > 1) {
    // Find custom endpoints section after the last auto-generated section
    const afterAutoGen = customEndpointsMatch[customEndpointsMatch.length - 1];
    const customMatch = afterAutoGen?.match(/\/\/\s*Custom endpoints([\s\S]*)/);
    if (customMatch) {
      return (
        customMatch[1]
          ?.split('\n')
          .filter((line) => {
            const trimmed = line.trim();
            return trimmed && !trimmed.startsWith('//') && trimmed !== '';
          })
          .join('\n') ?? ''
      );
    }
    return '';
  }

  // No auto-generated section exists yet, extract all as custom
  return content
    .split('\n')
    .filter((line) => {
      const trimmed = line.trim();
      return trimmed && !trimmed.startsWith('//') && trimmed !== '';
    })
    .join('\n');
}

/**
 * Generate endpoint mappings from models
 */
export function generateEndpointMappings(
  models: PrismaModel[],
  getResourceName: (modelName: string) => string,
  getApiEndpoint: (modelName: string) => string,
): string {
  return models
    .filter((model) => model.modulePath)
    .map((model) => {
      const resourceName = getResourceName(model.name);
      const apiEndpoint = getApiEndpoint(model.name);
      return `    '${resourceName}': '${apiEndpoint}'`;
    })
    .join(',\n');
}

/**
 * Build complete endpoint map string
 */
export function buildEndpointMap(autoGeneratedMappings: string, customEndpoints: string): string {
  let endpointMap = `const endpointMap: Record<string, string> = {\n`;
  endpointMap += `    // Auto-generated API endpoints\n`;

  if (autoGeneratedMappings.trim()) {
    endpointMap += autoGeneratedMappings;
  }

  if (customEndpoints.trim()) {
    if (autoGeneratedMappings.trim()) {
      endpointMap += `,\n    // Custom endpoints\n${customEndpoints}`;
    } else {
      // Only custom endpoints, add comma before if no auto-generated mappings
      endpointMap += customEndpoints;
    }
  }

  endpointMap += `\n  };`;
  return endpointMap;
}
